// === LEZIONE 060 ===
QUESTIONS.push(
  {id:"L60Q1", lesson:"060", type:"chiusa", question:"Che differenza c'è tra la ricerca di un nodo in una Lista ordinata o non ordinata?",
    options:["In media la ricerca in una lista ordinata è più efficiente","Possiamo effettuare la ricerca solo in liste ordinate","Possiamo partire dalla testa nel primo caso e dalla coda nel secondo caso","Sono identiche"],
    correct:0},
  {id:"L60Q2", lesson:"060", type:"chiusa", question:"Se effettuiamo la ricerca di un nodo in una Lista vuota:",
    options:["La ricerca non si può fare e viene generata un'eccezione di lista vuota","La ricerca va avanti e restituisce comunque un risultato","La JVM gestisce automaticamente l'eccezione rilevando che il primo nodo è null","Il compilatore genera un errore perchè rileva che il primo nodo è null"],
    correct:0},
  {id:"L60Q3", lesson:"060", type:"chiusa", question:"Dato un nodo di una classe Lista, l'istruzione \"aux = aux.getNext()\":",
    options:["Scorre in avanti al prossimo nodo assegnando al valore aux l'indirizzo contenuto in aux.next","E' ricorsiva e non si può eseguire","Scorre in avanti al prossimo nodo assegnando al valore aux l'indirizzo contenuto in aux","Scorre indietro al nodo precedente assegnando al valore aux l'indirizzo contenuto in aux"],
    correct:0},
  {id:"L60Q4", lesson:"060", type:"chiusa", question:"L'espressione \"(aux!=null && aux.getInfo()<key)\" con aux variabile ausiliaria Nodo di una Lista:",
    options:["Vale true se aux punta ad un nodo inesistente","Vale true se aux punta ad un nodo esistente (non nullo) o se il valore info contenuto nel nodo è minore di \"key\"","Vale true se aux punta ad un nodo esistente (non nullo) e se il valore info contenuto nel nodo è minore di \"key\"","Vale true se aux punta ad un nodo esistente (non nullo) e se l'attributo info contenuto nel nodo è maggiore di \"key\""],
    correct:2},
  {id:"L60Q5", lesson:"060", type:"chiusa", question:"Nel caso di ricerca di un nodo avente \"info=3\" in una Lista ordinata di interi:",
    options:["La ricerca visita la lista e per ogni nodo se trova il valore 3 si ferma e ritorna il riferimento al nodo","La ricerca visita la lista e per ogni nodo se trova il valore 3 continua a visitare e ritorna il riferimento al nodo","La ricerca visita tutta la lista e se trova il valore 3 in una info ritorna true e continua a visitare la lista","La ricerca visita tutta la lista e se trova il valore 3 in una info cancella il resto della lista e ritorna il riferimento al nodo"],
    correct:0},
  {id:"L60Q6", lesson:"060", type:"chiusa", question:"L'espressione \"(aux != null && aux.getInfo() == key)\" ritorna:",
    options:["True se il valore della variabile aux è null e se il contenuto dell'info nel nodo è diverso al valore key","True se il valore della variabile aux è non null e se il contenuto dell'info nel nodo è diverso al valore key","True se il valore della variabile aux è non null e se il contenuto dell'info nel nodo è pari al valore key","True se il valore della variabile aux è non null o se il contenuto dell'info nel nodo è diverso al valore key"],
    correct:2},
  {id:"L60Q7", lesson:"060", type:"chiusa", question:"La ricerca di un nodo in una Lista ordinata:",
    options:["E' possibile ma più complicata se la lista è ordinata","Non è possibile","E' possibile e se ordinata è più veloce","E' possibile ma dipende dal tipo di nodo"],
    correct:2},
  {id:"L60Q8", lesson:"060", type:"chiusa", question:"Per ricercare un valore in una lista:",
    options:["Si parte facendo assegnando null alla variabile temporanea aux di tipo Nodo","Si parte facendo puntare una variabile temporanea aux di tipo Nodo alla testa della lista","Si parte facendo puntare una variabile temporanea aux di tipo Nodo al centro della lista","Si parte facendo puntare una variabile temporanea aux di tipo Nodo alla coda della lista"],
    correct:1},
  {id:"L60Q9", lesson:"060", type:"aperta", question:"Scrivere in codice java e commentare un metodo di ricerca di un nodo in una Lista semplicemente linkata non ordinata.",
    options:[""],
    correct:0},
);

// === LEZIONE 061 ===
QUESTIONS.push(
  {id:"L61Q1", lesson:"061", type:"chiusa", question:"Se una Lista contiene un solo nodo:",
    options:["L'eliminazione di un nodo non si può fare","L'eliminazione di un nodo genera una lista vuota e la testa sarà settata automaticamente a null","L'eliminazione di un nodo si può fare ma la lista punta sempre alla testa","L'eliminazione di un nodo genera una lista vuota e la testa deve essere settata a null"],
    correct:3},
  {id:"L61Q2", lesson:"061", type:"chiusa", question:"Per eliminare il primo nodo di una Lista non vuota l'istruzione corretta è:",
    options:["\"head.info = null\" che setta a null il valore del puntatore di testa","\"head = head.getNext()\" che setta la testa al prossimo nodo","\"head = null\" che setta a null il nodo di testa","\"head.Next = null\" che setta a null il prossimo nodo"],
    correct:1},
  {id:"L61Q3", lesson:"061", type:"chiusa", question:"Se una Lista contiene due nodi e si vuole eliminare l'ultimo nodo:",
    options:["Il nodo di testa deve essere modificato settando il campo next pari a null","Il nodo di testa deve esser modificato settando il campo next pari al nodo eliminato","Il nodo di testa va eliminato","Il nodo di testa non deve essere modificato"],
    correct:0},
  {id:"L61Q4", lesson:"061", type:"chiusa", question:"Dati due nodi Nodo1 e Nodo2 di una Lista, cosa fa l'istruzione \"Nodo1.setNext(Nodo2.getNext())\"?",
    options:["Fa sì che entrambi i nodi abbiano lo stesso nodo successivo","Fa sì che il secondo nodo sia sostituito dal primo","Elimina la testa della Lista","Elimina il primo e il secondo nodo"],
    correct:0},
  {id:"L61Q5", lesson:"061", type:"chiusa", question:"Per eliminare l'ultimo nodo di una Lista semplicemente linkata:",
    options:["Basta partire dal nodo in coda","Basta eliminare il nodo di testa","Devo scorrere prima tutti i nodi della Lista partendo dalla coda","Devo scorrere prima tutti i nodi della Lista partendo dalla testa"],
    correct:3},
  {id:"L61Q6", lesson:"061", type:"chiusa", question:"In caso di cancellazione di un nodo intermedio di una Lista:",
    options:["Basta usare solo il riferimento al nodo di testa","Non serve nessuna variabile nodo ausiliaria perchè la lista rimane collegata","Serve avere un riferimento al nodo precedente ed uno al successivo per collegare la lista","Servono due riferimenti, uno alla testa ed uno alla coda della lista"],
    correct:2},
  {id:"L61Q7", lesson:"061", type:"chiusa", question:"La seguente istruzione \"head = head.getNext();\" che effetto ha su una Lista?",
    options:["Si usa per inserire un elemento in testa ad una lista","Si usa per cancellare una intera lista","Si usa per cancellare il primo elemento di una lista","Si usa per duplicare l'elemento in testa ad una lista"],
    correct:2},
  {id:"L61Q8", lesson:"061", type:"chiusa", question:"Per eliminare un nodo da una Lista:",
    options:["E' necessario manipolare gli attributi next dei nodi in modo da lasciare la struttura sempre concatenata","E' necessario manipolare solo la testa della lista","Non serve considerare la posizione del nodo","E' necessario manipolare gli attributi info dei nodi in modo da lasciare la struttura sempre concatenata"],
    correct:0},
  {id:"L61Q9", lesson:"061", type:"aperta", question:"Scrivere in codice Java e commentare un metodo che effettui l'eliminazione del nodo di testa di una Lista semplicemente linkata.",
    options:[""],
    correct:0},
);

// === LEZIONE 062 ===
QUESTIONS.push(
  {id:"L62Q1", lesson:"062", type:"chiusa", question:"In caso di Lista doppiamente linkata:",
    options:["E' possibile scorrere la lista solo a partire dalla testa","Non è possibile scorrere la lista in due direzioni","E' possibile scorrere la lista solo a partire dalla coda","E' possibile scorrere la lista in due direzioni"],
    correct:3},
  {id:"L62Q2", lesson:"062", type:"chiusa", question:"Il Nodo di una Lista può contenere una stringa?",
    options:["No perchè non fa parte del dominio numerico","Basta creare opportunamente l'attributo info della classe Nodo","Nella classe Nodo possono essere memorizzati solo tipi numerici","Non si può rappresentare come stringa ma solo come array di caratteri"],
    correct:1},
  {id:"L62Q3", lesson:"062", type:"chiusa", question:"Nell'implementazione di una Lista doppiamente linkata, quando si trova l'istruzione \"head=new NodoDL(val)\"?",
    options:["Quando la lista è non vuota e si vuole inserire un nodo valore \"val\"","Quando la lista è vuota e si vuole inserire un nodo con valore \"val\"","Quando si vuole inserire un nodo con valore \"val\" in testa","Mai perchè è errata"],
    correct:1},
  {id:"L62Q4", lesson:"062", type:"chiusa", question:"In caso di Lista doppiamente linkata contenente solo nodo:",
    options:["Il puntatore alla coda punta a null","Il puntatore alla coda e alla testa non hanno lo stesso valore","Il puntatore alla coda e alla testa puntano a null","Il puntatore alla coda e alla testa hanno lo stesso valore"],
    correct:3},
  {id:"L62Q5", lesson:"062", type:"chiusa", question:"Nell'implementazione di una Lista, l'istruzione \"head.getNext()==null\" ritorna true se:",
    options:["La lista non contiene alcun nodo","La lista contiene almeno un nodo null","La lista contiene uno e un solo nodo","La lista contiene due nodi di cui il secondo punta a null"],
    correct:2},
  {id:"L62Q6", lesson:"062", type:"chiusa", question:"Una Lista doppiamente linkata ha il nodo di testa tale che:",
    options:["Ha un puntatore punta al primo nodo e uno che punta a null","Ha un puntatore punta al secondo e uno al terzo nodo","Ha un puntatore punta al primo e uno al terzo nodo","Ha un puntatore punta al primo e uno al secondo nodo"],
    correct:0},
  {id:"L62Q7", lesson:"062", type:"chiusa", question:"In una Lista doppiamente linkata:",
    options:["Si può inserire un nodo intermedio solo creando una copia dei nodi","La rimozione di un nodo intermedio è più semplice rispetto alla Lista semplicemente linkata","Non si può inserire direttamente il nodo di coda senza scorrere tutti gli elementi","Inserire un nodo solo partendo dalla testa"],
    correct:1},
  {id:"L62Q8", lesson:"062", type:"chiusa", question:"Una lista doppiamente linkata:",
    options:["E' una lista in cui ogni nodo ha un puntatore al successivo ed uno al precedente","E' una lista doppia","E' una lista in cui ogni nodo può memorizzare due valori","E' l'unico tipo di lista in cui i nodi sono collegati fra loro"],
    correct:0},
  {id:"L62Q9", lesson:"062", type:"aperta", question:"Descrivere la struttura di una Lista doppiamente linkata e scrivere il codice della classe in linguaggio Java.",
    options:[""],
    correct:0},
  {id:"L62Q10", lesson:"062", type:"aperta", question:"Descrivere la struttura di un Nodo per una Lista doppiamente linkata e scrivere il codice della classe in linguaggio Java.",
    options:[""],
    correct:0},
);

// === LEZIONE 063 ===
QUESTIONS.push(
  {id:"L63Q1", lesson:"063", type:"chiusa", question:"In un Albero Binario Completo (ovvero ogni nodo ha due figli) al livello K ci sono:",
    options:["2^(K-1) nodi","K^2 nodi","2^K nodi","2^(K-2) nodi"],
    correct:2},
  {id:"L63Q2", lesson:"063", type:"chiusa", question:"In una struttura dati Albero, un nodo senza figli si chiama:",
    options:["Radice","Figlio","Ramo","Foglia"],
    correct:3},
  {id:"L63Q3", lesson:"063", type:"chiusa", question:"In un Albero Binario:",
    options:["Ogni nodo ha due archi (binari)","Ogni nodo ha due padri","Solo la Radice può avere due figli","Ogni nodo ha al più due figli"],
    correct:3},
  {id:"L63Q4", lesson:"063", type:"chiusa", question:"Che caratteristica deve avere un nodo interno di un Albero?",
    options:["deve avere almeno due figli","deve avere almeno un figlio","deve avere dei fratelli","deve essere un nodo Foglia"],
    correct:1},
  {id:"L63Q5", lesson:"063", type:"chiusa", question:"Un Albero è una struttura dati fatta da nodi e connessioni detti rami dove:",
    options:["Ogni nodo è autonomo e non raggiungibile","Ogni nodo è raggiungibile da ogni altro nodo","Ogni nodo è il padre di tutti i nodi","Ogni nodo (eccetto il nodo radice) è connesso tramite un ramo ad un altro nodo, che ne è il padre, e di cui rappresenta il figlio"],
    correct:3},
  {id:"L63Q6", lesson:"063", type:"chiusa", question:"In una struttura dati Albero, un cammino con K nodi ha:",
    options:["K archi e lunghezza K-1","K-1 archi e lunghezza K","K+1 archi, ovvero ha lunghezza K+1","K-1 archi, ovvero ha lunghezza K-1"],
    correct:0},
  {id:"L63Q7", lesson:"063", type:"chiusa", question:"Dato un Albero, il numero di archi coinvolti in un cammino si chiama:",
    options:["Altezza del cammino","Lunghezza del cammino","Altezza dell'Albero","Profondità del cammino"],
    correct:1},
  {id:"L63Q8", lesson:"063", type:"chiusa", question:"La ricerca di nodi in un Albero implica:",
    options:["Uguale numero di passi rispetto ad una lista","Un numero di passi maggiore rispetto a una lista","Nessun attraversamento di nodi","Un numero di passi minore rispetto a una lista"],
    correct:2},
);

// === LEZIONE 064 ===
QUESTIONS.push(
  {id:"L64Q1", lesson:"064", type:"chiusa", question:"La struttura Nodo di un Albero binario ricorda:",
    options:["L'implementazione degli array nelle stringhe","L'implementazione delle stringhe di caratteri","L'implementazione dei vettori negli array","L'implementazione dei Nodi della struttura dati Lista"],
    correct:3},
  {id:"L64Q2", lesson:"064", type:"chiusa", question:"La classe Nodo di un Albero Binario:",
    options:["Deve contenere due attributi info","Deve contenere almeno due attributi nodo e un attributi info","Deve contenere almeno due attributi info e un attributo nodo","Deve contenere almeno due attributi info"],
    correct:1},
  {id:"L64Q3", lesson:"064", type:"chiusa", question:"In un Albero Binario la visita Preorder:",
    options:["Visita la radice, visita ricorsivamente il sotto-albero sinistro, visita ricorsivamente il sotto-albero destro","Visita il nodo destro, visita la radice, visita ricorsivamente il sotto-albero sinistro","Visita la radice, visita ricorsivamente il sotto-albero destro, visita ricorsivamente il sotto-albero sinistro","Visita il nodo sinistro, visita la radice, visita ricorsivamente il sotto-albero destro"],
    correct:0},
  {id:"L64Q4", lesson:"064", type:"chiusa", question:"In un Albero Binario la visita Postorder:",
    options:["Visita la radice, visita ricorsivamente il sotto-albero destro, visita il sotto-albero sinistro","Visita il nodo destro, visita la radice, visita ricorsivamente il sotto-albero sinistro","Visita il ricorsivamente sotto-albero sinistro, visita ricorsivamente il sotto-albero destro, visita la radice","Visita il nodo sinistro, visita la radice, visita ricorsivamente il sotto-albero destro"],
    correct:2},
  {id:"L64Q5", lesson:"064", type:"chiusa", question:"Un Albero Binario si costruisce con una classe Nodo che contiene:",
    options:["Un intero per il figlio sinistro e un intero per il figlio destro","L'informazione, un oggetto Nodo figlio sinistro e un oggetto Nodo figlio destro","Un intero per il figlio sinistro, un intero per il figlio destro, un oggetto Nodo per l'informazione","L'informazione, un intero per il figlio sinistro e un intero per il figlio destro"],
    correct:1},
  {id:"L64Q6", lesson:"064", type:"chiusa", question:"In un Albero Binario:",
    options:["La connessione tra nodi si implementa con i numeri","La connessione tra nodi si implementa con i puntatori","La connessione tra nodi si implementa con i double","La connessione tra nodi si implementa con gli interi"],
    correct:1},
  {id:"L64Q7", lesson:"064", type:"chiusa", question:"In quale visita degli Alberi Binari si stampa prima l'info del nodo e poi si visitano il sotto-albero sinistro e poi il sotto-albero destro?",
    options:["Nella visita Inorder","Nella visita Firstorder","Nella visita Preorder","Nella visita Postorder"],
    correct:2},
  {id:"L64Q8", lesson:"064", type:"chiusa", question:"Nelle visite Preoder, Inorder e Postorder di un Albero Binario, quale tecnica si usa per visitare i nodi?",
    options:["Si usa la riflessione","Si usa un ciclo for","Si usa la ricorsione","Si usa l'iterazione"],
    correct:2},
  {id:"L64Q9", lesson:"064", type:"aperta", question:"Descrivere la struttura del Nodo di un Albero Binario e scrivere il codice della classe in linguaggio Java.",
    options:[""],
    correct:0},
  {id:"L64Q10", lesson:"064", type:"aperta", question:"Descrivere la struttura di un Albero Binario e scrivere il codice della classe in linguaggio Java.",
    options:[""],
    correct:0},
);

// === LEZIONE 065 ===
QUESTIONS.push(
  {id:"L65Q1", lesson:"065", type:"chiusa", question:"Il Collections Framework di Java contiene:",
    options:["Solo interfacce e classi astratte","Solo classi astratte","Interfacce, classi astratte e classi concrete","Solo interfacce"],
    correct:2},
  {id:"L65Q2", lesson:"065", type:"chiusa", question:"Le interfacce del Collections Framework di Java sono contenute:",
    options:["Nel package java.io","Nel package javax.swing","Nel package java.util","Nel package java.lang"],
    correct:2},
  {id:"L65Q3", lesson:"065", type:"chiusa", question:"Le Liste del Collections Framework di Java:",
    options:["Non hanno nulla a che vedere con il concetto matematico di insieme","Sono collezioni di tipi base di Java","Implementano l'interfaccia Collection","Non hanno nulla a che vedere con le collezioni"],
    correct:2},
  {id:"L65Q4", lesson:"065", type:"chiusa", question:"Il metodo \"boolean add(Object o)\" di una Collection Java:",
    options:["Verifica se si può aggiungere un elemento alla collezione (ritorna false se non è possibile)","Aggiunge un elemento alla collezione (ritorna true se non è possibile aggiungerlo)","Verifica se si può aggiungere un elemento alla collezione (ritorna true se è possibile)","Aggiunge un elemento alla collezione (ritorna false se non è possibile aggiungerlo)"],
    correct:0},
  {id:"L65Q5", lesson:"065", type:"chiusa", question:"Il metodo \"boolean removeAll(Collection c)\" di una Collection Java:",
    options:["Rimuove gli elementi della collezione passata come parametro che esistono nella collezione corrente e torna true se la collezione è stata modificata","Rimuove alcuni elementi della collezione passata come parametro che esistono nella collezione corrente e torna un boolean","Rimuove dalla collezione passata come parametro gli elementi che esistono anche nella collezione corrente e torna true se la collezione c è stata modificata","Svuota la collezione c passata come parametro"],
    correct:0},
  {id:"L65Q6", lesson:"065", type:"chiusa", question:"Il metodo boolean \"containsAll(Collection c)\" di una Collection Java:",
    options:["Ritorna true se tutti gli elementi della collezione c passata come parametro sono contenuti anche nella collezione corrente","Ritorna true se la collezione c passata come parametro contiene gli stessi elementi della collezione corrente","Ritorna true se la collezione c è piena","Ritorna true se la collezione c è vuota"],
    correct:0},
  {id:"L65Q7", lesson:"065", type:"chiusa", question:"Il metodo void \"clear()\" di una Collection Java:",
    options:["Elimina dalla collezione gli elementi nulli","Elimina la collezione dalla memoria","Elimina dalla collezione di tutti gli elementi","Elimina dalla collezione gli elementi non permanenti"],
    correct:2},
  {id:"L65Q8", lesson:"065", type:"chiusa", question:"Il metodo \"Collection.iterator()\" di una Collection Java:",
    options:["Ritorna una istanza di Iterator che possiamo usare la testa della collezione","Ritorna una istanza di Iterator che possiamo usare per leggere il primo elemento della collezione","Ritorna una istanza di Iterator che possiamo usare per scorrere ed eliminare gli elementi della collezione","Ritorna una istanza di Iterator che possiamo usare per rimuovere solo gli elementi finali della collezione"],
    correct:2},
  {id:"L65Q9", lesson:"065", type:"aperta", question:"Descrivere il ruolo di ciascuna delle interfacce Collection, List, Set e Queue e il rapporto che esiste fra di loro in termini di gerarchia.",
    options:[""],
    correct:0},
  {id:"L65Q10", lesson:"065", type:"aperta", question:"Descrivere che cos'è il Collections Framework di Java ed elencare le interfacce principali.",
    options:[""],
    correct:0},
);

// === LEZIONE 066 ===
QUESTIONS.push(
  {id:"L66Q1", lesson:"066", type:"chiusa", question:"Quale fra le seguenti affermazioni è falsa se riferita ad un ArrayList?",
    options:["La sua implementazione interna è basata su array","E' un oggetto immutabile","Eredita caratteristiche da Collection","L'aggiunta di nuovi elementi può essere molto poco efficiente"],
    correct:1},
  {id:"L66Q2", lesson:"066", type:"chiusa", question:"Quale fra le seguenti affermazioni è falsa se riferita ad una LinkedList?",
    options:["Non è immutabile","L'accesso ai suoi elementi è meno efficiente rispetto ad un ArrayList","L'inserimento e la rimozione di elementi è più efficiente rispetto ad un ArrayList","L'inserimento e la modifica degli elementi sono in media sono poco efficienti"],
    correct:3},
  {id:"L66Q3", lesson:"066", type:"chiusa", question:"Quale fra le seguenti inizializzazioni di un ArrayList è errata?",
    options:["ArrayList a = new ArrayList();","Collection a = new ArrayList();","ArrayList a = new ArrayList(10);","LinkedList a = new ArrayList();"],
    correct:3},
  {id:"L66Q4", lesson:"066", type:"chiusa", question:"Quale fra le seguenti affermazioni è falsa se riferita ad un ArrayList?",
    options:["L'accesso ai suoi elementi è più efficiente rispetto ad una LinkedList","Le operazioni di inserimento sono potenzialmente poco costose","L'inserimento e la rimozione di elementi è più meno efficiente rispetto ad un ArrayList","Non è immutabile"],
    correct:2},
  {id:"L66Q5", lesson:"066", type:"chiusa", question:"Come si scorrono gli elementi di una Collection?",
    options:["Dipende dalla sottoclasse concreta che si sta considerando","Con un oggetto di tipo Iterator","Iterando un oggetto wrapper numerico","Con un puntatore a Collection"],
    correct:1},
  {id:"L66Q6", lesson:"066", type:"chiusa", question:"Qual è la differenza tra le classi ArrayList e LinkedList?",
    options:["ArrayList è implementata con un array, LinkedList con una lista","Sono identiche","ArrayList contiene solo oggetti di tipo array","ArrayList contiene array, LinkedList contiene liste"],
    correct:0},
  {id:"L66Q7", lesson:"066", type:"chiusa", question:"Come vengono utilizzate le classi wrapper dei tipi numerici nelle Liste?",
    options:["A permettere alle sottoclassi del Collections Framework di contenere numeri","A permettere a un Iterator di manipolare numeri","A permettere alle sottoclassi dei Collection di leggere numeri dalla tastiera","A permettere a una Collection di wrappare oggetti"],
    correct:0},
  {id:"L66Q8", lesson:"066", type:"chiusa", question:"Qual è lo scopo delle classi wrapper dei tipi numerici?",
    options:["A wrappare oggetti primitivi","A contenere tipi numerici primitivi","A contenere oggetti di tipo numerico","A manipolare oggetti numerici"],
    correct:1},
  {id:"L66Q9", lesson:"066", type:"aperta", question:"Descrivere le principali differenze tra ArrayList e LinkedList, fornendo degli esempi di codice.",
    options:[""],
    correct:0},
  {id:"L66Q10", lesson:"066", type:"aperta", question:"Descrivere le principali classi wrapper Java dei tipi numerici.",
    options:[""],
    correct:0},
);

// === LEZIONE 067 ===
QUESTIONS.push(
  {id:"L67Q1", lesson:"067", type:"chiusa", question:"A cosa serve l'operatore diamond di Java?",
    options:["Permette di aggiungere tipi numerici in una Lista","Permette di restringere gli oggetti che si possono aggiungere a una Collection","A far funzionare il Collections Framework","Permette di utilizzare i tipi wrapper numerici"],
    correct:1},
  {id:"L67Q2", lesson:"067", type:"chiusa", question:"Cosa è falso se riferito all'operatore diamond di Java?",
    options:["Permette di definire metodi generici","Funziona con tutti le classi Java","Permette di definire classi generiche","Funziona solo con le classi wrapper numeriche"],
    correct:3},
  {id:"L67Q3", lesson:"067", type:"chiusa", question:"L'operatore diamond di Java:",
    options:["Permette di specificare vincoli sui tipi che si possono passare ad un metodo","Permette di evitare cast impliciti","Permette di restringere i tipi utilizzabili","Permette di evitare cast espliciti"],
    correct:3},
  {id:"L67Q4", lesson:"067", type:"chiusa", question:"La correttezza delle operazioni vincolate con l'operatore diamond:",
    options:["Viene controllata dal compilatore","Viene controllata a tempo di esecuzione","Deve essere controllata dall'utente","Viene controllata dalla Java Virtual Machine"],
    correct:0},
  {id:"L67Q5", lesson:"067", type:"chiusa", question:"Cosa è falso se riferito alla definizione \"LinkedList list = new LinkedList<>();\":",
    options:["Demandiamo il controllo al compilatore circa gli oggetti inseriti in list","Se nella lista inseriamo un Double, a tempo di esecuzione verrà lanciata una eccezione","Restringiamo gli oggetti che si possono inserire in list alla classe Integer","Definiamo una Lista che accetta solo istanze della classe Integer"],
    correct:1},
  {id:"L67Q6", lesson:"067", type:"chiusa", question:"Come possiamo limitare gli oggetti generici di un metodo o di una classe?",
    options:["In nessun modo","Possiamo restringerli alle classi di un certo package","Possiamo restringerli ai tipi base","Possiamo restringerli ad una certa gerarchia di classi"],
    correct:3},
  {id:"L67Q7", lesson:"067", type:"chiusa", question:"Il metodo \"public Collection operazione(T[] a)\":",
    options:["Ritorna una istanza della classe generica T","Per farlo funzionare dobbiamo definire la classe T nel file T.java","Ritorna un oggetto del tipo base T","Ritorna una istanza di Collection contenente oggetti di tipo T"],
    correct:3},
  {id:"L67Q8", lesson:"067", type:"chiusa", question:"Il metodo definito come \"public T metodo()\":",
    options:["Restringe il tipo T alla interfaccia Comparable ed estende Number","Dice che il tipo T può estendere sia Number che Comparable","Restringe il tipo T alla classe Number o alla interfaccia Comparable","Dice che il tipo T deve estendere Number ed implementare Comparable"],
    correct:3},
  {id:"L67Q9", lesson:"067", type:"aperta", question:"Descrivere che cos'è e a che cosa serve l'operatore diamond in Java e fornire degli esempi di codice.",
    options:[""],
    correct:0},
  {id:"L67Q10", lesson:"067", type:"aperta", question:"Descrivere che cos'è un metodo generico in Java e fornire un esempio utilizzando il codice Java.",
    options:[""],
    correct:0},
);

// === LEZIONE 068 ===
QUESTIONS.push(
  {id:"L68Q1", lesson:"068", type:"chiusa", question:"Che cos'è la complessità computazionale?",
    options:["Una misura del tempo di esecuzione di un algoritmo sun certo hardware","Una misura legata all'efficienza di un algoritmo al variare dell'input","Un modo per capire quanta memoria occupa un algoritmo","Un modo per misurare quanto è difficile un algoritmo"],
    correct:1},
  {id:"L68Q2", lesson:"068", type:"chiusa", question:"In termini matematico-insiemistici, un problema può essere visto come:",
    options:["Una funzione tra due insiemi, l'insieme degli input e quello degli output","Una funzione tra i parametri e il tipo di ritorno","Una funzione tra due insiemi, l'insieme delle istanze e quello delle soluzioni","L'algoritmo che lo implementa"],
    correct:2},
  {id:"L68Q3", lesson:"068", type:"chiusa", question:"Per definizione, un Algoritmo deve essere:",
    options:["non ambiguo","finito, non ambiguo e terminante","finito e non ambiguo","finito, efficiente e terminante"],
    correct:1},
  {id:"L68Q4", lesson:"068", type:"chiusa", question:"Un Algoritmo che non termina mai:",
    options:["è inaccettabile perchè occupa inutilmente risorse computazionali","in realtà non è un Algoritmo","è molto poco efficiente","è accettabile perchè non spreca memoria"],
    correct:1},
  {id:"L68Q5", lesson:"068", type:"chiusa", question:"In generale, il tempo di esecuzione di un Algoritmo:",
    options:["Aumenta con l'aumentare della dimensione dell'input","Dipende da molti fattori che non possono essere previsti","Dipende dall'hardware su cui gira ma è indipendente dai dati","E' sempre costante"],
    correct:0},
  {id:"L68Q6", lesson:"068", type:"chiusa", question:"La dipendenza di un Algoritmo tra la dimensione dell'input e il tempo di esecuzione:",
    options:["Dipende da come l'Algoritmo è stato implementato","Dipende solo dall'hardware","Dipende da innumerevoli fattori","Non può essere determinato"],
    correct:0},
  {id:"L68Q7", lesson:"068", type:"chiusa", question:"Per effettuare l'Analisi di complessità di un Algoritmo:",
    options:["Bisogna considerare la quantità di RAM occupata e la potenza della CPU","Bisogna tenere in considerazione l'hardware su cui gira","Non è utile considerare il suo tempo di esecuzione","Bisogna considerare il linguaggio di programmazione utilizzato"],
    correct:0},
  {id:"L68Q8", lesson:"068", type:"chiusa", question:"Per valutare le prestazioni di un Algoritmo:",
    options:["Non possiamo usare nulla","Si usa il tempo di esecuzione","Si usa la quantità di memoria occupata","Non viene mai usato il tempo di esecuzione"],
    correct:1},
);

// === LEZIONE 070 ===
QUESTIONS.push(
  {id:"L70Q1", lesson:"070", type:"aperta", question:"Descrivere che cos'è la notazione O-grande e fornire degli esempi.",
    options:[""],
    correct:0},
);

// === LEZIONE 071 ===
QUESTIONS.push(
  {id:"L71Q1", lesson:"071", type:"chiusa", question:"Per rilevare l'istante temporale in cui si verifica un evento, la classe StopWatch:",
    options:["Chiede il tempo alla Java Virtual Machine","Chiede il tempo al Sistema Operativo","Chiede il tempo ad una classe della libreria standard di Java","Chiede il tempo alla superclasse"],
    correct:2},
  {id:"L71Q2", lesson:"071", type:"chiusa", question:"Per misurare l'efficienza dei propri algoritmi possiamo:",
    options:["Utilizzare la classe StopWatch","Utilizzare un cronografo automatico di precisione","Utilizzare un cronometro","Utilizzare la classe Swatch"],
    correct:0},
  {id:"L71Q3", lesson:"071", type:"chiusa", question:"Cosa è falso se riferito alla classe StopWatch?",
    options:["Posso misurare il tempo trascorso dall'avvio della Java Virtual Machine","Posso misurare l'efficienza di un algoritmo","Posso misurare il tempo trascorso tra due eventi","Posso misurare sia i tempi intermedi che il tempo totale"],
    correct:0},
  {id:"L71Q4", lesson:"071", type:"chiusa", question:"Cosa è falso se riferito alla funzione System.currentTimeMillis()?",
    options:["Si può utilizzare per misurare il tempo CPU del Sistema Operativo","Si può utilizzare per misurare il tempo trascorso fra due eventi","Si può utilizzare per misurare l'efficienza di un algoritmo","Si può utilizzare per contare i millisecondi trascorsi dal 1 gennaio 1970"],
    correct:0},
  {id:"L71Q5", lesson:"071", type:"chiusa", question:"La classe StopWatch misura il tempo:",
    options:["Calcolando la differenza in millisecondi tra due misurazioni","Effettuando una chiamata alla Java Virtual Machine","Effettuando una chiamata al Sistema Operativo","Calcolando la differenza in secondi tra due misurazioni"],
    correct:0},
  {id:"L71Q6", lesson:"071", type:"chiusa", question:"Dopo aver creato una nuova istanza di StopWatch con \"StopWatch t = new StopWatch();\" con t.start():",
    options:["Si avvia il timer della Java Virtual Machine","Si avvia il timer di Sistema","Si avvia il timer dell'algoritmo","Si avvia il timer dell'oggetto StopWatch"],
    correct:3},
  {id:"L71Q7", lesson:"071", type:"chiusa", question:"Il metodo getElapsedTime() della class StopWatch:",
    options:["Misura il tempo trascorso dall'avvio della macchina","Misura il tempo trascorso fra due eventi in secondi","Misura il tempo trascorso fra due eventi in millisecondi","Misura il tempo trascorso dalla new della classe StopWatch"],
    correct:2},
  {id:"L71Q8", lesson:"071", type:"chiusa", question:"La classe StopWatch vista a lezione:",
    options:["Serve ad implementare un orologio grafico","Serve a fermare ed avviare un algoritmo","Serve a migliorare le prestazioni di un algoritmo","Serve a misurare il tempo fra due eventi"],
    correct:3},
);

// === LEZIONE 072 ===
QUESTIONS.push(
  {id:"L72Q1", lesson:"072", type:"chiusa", question:"La funzione di complessità \"T(n)=3*n^2+log(n)+5\" ha complessità asintotica:",
    options:["Lineare","Logaritmica","Quadratica","Costante"],
    correct:2},
  {id:"L72Q2", lesson:"072", type:"chiusa", question:"Cosa possiamo concludere sulla funzione di complessità \"T(n)=n+1000\"?",
    options:["La complessità asintotica è lineare","La complessità può essere costante per qualche n","La complessità è costante","La complessità è sempre lineare"],
    correct:0},
  {id:"L72Q3", lesson:"072", type:"chiusa", question:"La funzione di complessità \"T(n)=log(n)+3n+5\" ha complessità asintotica:",
    options:["è O(log(n))","è O(n+log(n))","è O(n)","è O(n^2)"],
    correct:2},
  {id:"L72Q4", lesson:"072", type:"chiusa", question:"La funzione di complessità \"T(n)=n^3+7n+2\" ha complessità asintotica:",
    options:["Cubica","Costante","Lineare","Quadratica"],
    correct:0},
  {id:"L72Q5", lesson:"072", type:"chiusa", question:"Quali tipi di complessità esistono?",
    options:["La complessità del caso peggiore","La complessità asintotica e quella lineare","La complessità del caso peggiore, del caso migliore e del caso medio","La complessità del caso peggiore e del caso migliore"],
    correct:2},
  {id:"L72Q6", lesson:"072", type:"chiusa", question:"Cosa si può concludere circa la complessità asintotica di un doppio ciclo for innestato?",
    options:["La sua complessità è O(n^2)","La sua complessità è sempre quadratica","Se entrambe le variabili di ciclo variano da 0 ad n, la sua complessità è n^2","La sua complessità è lineare"],
    correct:2},
  {id:"L72Q7", lesson:"072", type:"chiusa", question:"Cosa è falso se riferito alla complessità di un doppio ciclo for innestato?",
    options:["La sua complessità è O(n^2)","La sua complessità dipende dal numero di cicli","La sua complessità dipende dal numero di operazioni","La sua complessità massima è O(n^2)"],
    correct:1},
  {id:"L72Q8", lesson:"072", type:"chiusa", question:"Cosa è falso se riferito alla complessità di un triplo ciclo for innestato?",
    options:["La sua complessità massima è O(n^3)","La sua complessità dipende dal numero di cicli","La sua complessità dipende dal numero di operazioni","La sua complessità è O(n^3)"],
    correct:1},
  {id:"L72Q9", lesson:"072", type:"aperta", question:"Dato un certo problema P e due algoritmi A e B che lo risolvono esntrambi ma in modo diverso, come faccio a scegliere il migliore fra i due? Discutere la problematica in termini di complessità degli algoritmi e fornire un esempio usando la notazione O-grande.",
    options:[""],
    correct:0},
  {id:"L72Q10", lesson:"072", type:"aperta", question:"Dato l'array \"int[][] a = new int[n][n];\" scrivere il codice per inizializzare i suoi elementi tutti al valore 5 e poi calcolarne la funzione di complessità asintotica.",
    options:[""],
    correct:0},
);

// === LEZIONE 073 ===
QUESTIONS.push(
  {id:"L73Q1", lesson:"073", type:"chiusa", question:"Come si fa ad avviare un nuovo Thread in Java?",
    options:["Si usa il metodo thread()","Si usa il metodo avvia()","Si usa il metodo start()","Si usa il metodo run()"],
    correct:2},
  {id:"L73Q2", lesson:"073", type:"chiusa", question:"Un Thread in Java:",
    options:["Viene eseguito all'interno del contesto di esecuzione di un processo (o programma)","Viene eseguito all'esterno del contesto di esecuzione di un processo (o programma)","Viene eseguito in autonomia da un file .exe","Viene eseguito in parallelo del contesto di esecuzione di un processo (o programma)"],
    correct:0},
  {id:"L73Q3", lesson:"073", type:"chiusa", question:"Per implementare un Thread in Java:",
    options:["Si estende la classe \"Execute\" oppure si implementa l'interfaccia \"Thread\"","Si estende la classe \"Thread\" oppure si implementa l'interfaccia \"Runnable\"","Si estende la classe \"Runnable\" oppure si implementa l'interfaccia \"Thread\"","Si estende l'interfaccia \"Thread\" oppure si implementa l'interfaccia \"Thread\""],
    correct:1},
  {id:"L73Q4", lesson:"073", type:"chiusa", question:"All'interno di un programma Java:",
    options:["E' possibile eseguire più di un thread","E' possibile eseguire un solo thread","E' possibile eseguire solo thread multipli dello stesso tipo","Non è possibile eseguire un solo thread ma più di uno"],
    correct:0},
  {id:"L73Q5", lesson:"073", type:"chiusa", question:"Le principali fasi di un Thread sono:",
    options:["Creazione, esecuzione, sospensione e terminazione","Creazione, dedalock e cancellazione","Sospensione, terminazione, cancellazione","Cancellazione, creazione, esecuzione continua"],
    correct:0},
  {id:"L73Q6", lesson:"073", type:"chiusa", question:"Due Thread Java possono essere eseguiti contemporaneamente?",
    options:["Vero ma solo se sono Thread con metodi run() vuoti","Vero, basta avviarli uno dopo l'altro","Dipende da quante CPU ha la macchina su cui vengono eseguiti","Falso non possono andare insieme in esecuzione"],
    correct:2},
  {id:"L73Q7", lesson:"073", type:"chiusa", question:"Se T1 è un Thread Java, l'invocazione al metodo T1.stop():",
    options:["Serve a fermare l'esecuzione di T1","Causa lo stop della Java Virtual Machine","Serve a sospendere temporaneamente l'esecuzione di T1","Serve a chiudere T1 e tornare al Sistema Operativo"],
    correct:0},
  {id:"L73Q8", lesson:"073", type:"chiusa", question:"Il metodo suspend() della classe Thread:",
    options:["Blocca l'esecuzione del Thread in attesa di succesiva resume","Blocca l'esecuzione del Thread in attesa di succesiva rerun","Blocca l'esecuzione del Thread in attesa di succesiva start","Cancella l'esecuzione del Thread in attesa di succesiva resume"],
    correct:0},
  {id:"L73Q9", lesson:"073", type:"aperta", question:"Descrivere cosa sono e a che servono i Thread in Java e illustrare le modalità per crearli in termini di codice Java.",
    options:[""],
    correct:0},
  {id:"L73Q10", lesson:"073", type:"aperta", question:"Usando il codice Java scrivere una semplice classe Thread che stampi 1000 volte il nome del proprio genere musicale preferito a video.",
    options:[""],
    correct:0},
);

// === LEZIONE 074 ===
QUESTIONS.push(
  {id:"L74Q1", lesson:"074", type:"chiusa", question:"Nel formato DateFormat.SHORT, la data 4 Luglio del 2021 viene formattata come:",
    options:["04/07/21","data di domenica, 4 luglio 2021","4 luglio 2021","domenica 4 luglio 2021"],
    correct:0},
  {id:"L74Q2", lesson:"074", type:"chiusa", question:"Data l'istruzione Java \"Date d = new Date(long n);\":",
    options:["Crea una data a partire dall'anno 0 + \"n\" giorni","Crea una data a partire da numeri lunghi","Crea una data a partire dal 1 gennaio 1970 + \"n\" millisecondi","Crea una data a partire dall'anno \"n\""],
    correct:2},
  {id:"L74Q3", lesson:"074", type:"chiusa", question:"La classe SimpleDateFormat di Java:",
    options:["Permette di convertire stringhe in date e viceversa","Converte stringhe in intervalli temporali","Permette di usare solo date corte","Converte date semplici dal formato inglese a quello italiano"],
    correct:0},
  {id:"L74Q4", lesson:"074", type:"chiusa", question:"La casse Date di Java è nel package:",
    options:["java.calendar","java.lang","java.io","java.util"],
    correct:3},
  {id:"L74Q5", lesson:"074", type:"chiusa", question:"La classe Calendar di Java:",
    options:["Permette di ottenere l'ora di sistema","Si usa per ottenere un oggetto calendario contenente tutte le date","Permette di effettuare operazioni numeriche con le date","Aggiorna il calendario del Sistema Operativo"],
    correct:2},
  {id:"L74Q6", lesson:"074", type:"chiusa", question:"Il metodo \"Date parse(String data)\" della classe DateFormat:",
    options:["Scrive una rappresentazione stringa di una data in output","Converte una stringa di una data in millisecondi","Converte una rappresentazione stringa di una data in una istanza della classe Date","Converte una rappresentazione di data Date in una istanza della classe String"],
    correct:2},
  {id:"L74Q7", lesson:"074", type:"chiusa", question:"Il metodo \"String format(Date data)\" della classe DateFormat:",
    options:["Converte una istanza di Date in una stringa","Converte una istanza di Millisecondi in una stringa","Converte una istanza di Minuti in una stringa","Converte una istanza di Ore in una stringa"],
    correct:0},
  {id:"L74Q8", lesson:"074", type:"chiusa", question:"La classe Date in Java:",
    options:["Si usa per gestire flussi di dati temporali dallo standard input","Si usa per modificare il tempo di esecuzione","Si usa per gestire l'orologio del PC","Si usa per gestire variabili che contengono istanti temporali"],
    correct:3},
  {id:"L74Q9", lesson:"074", type:"aperta", question:"Descrivere che cos'è e come si usa il metodo System.currentTimeMillis() e fornire un esempio in codice Java.",
    options:[""],
    correct:0},
  {id:"L74Q10", lesson:"074", type:"aperta", question:"Descrivere le differenze principali tra le classi Date, Calendar e SimpleDateFormat.",
    options:[""],
    correct:0},
);

// === LEZIONE 075 ===
QUESTIONS.push(
  {id:"L75Q1", lesson:"075", type:"chiusa", question:"La classe Permission fa parte del package:",
    options:["java.runnable","java.io","java.thread","java.security"],
    correct:3},
  {id:"L75Q2", lesson:"075", type:"chiusa", question:"Quale fra le seguenti è la definizione corretta per la classe Permission?",
    options:["E' una classe astratta che serve a rappresentare le varie modalità di esecuzione delle risorse del sistema","E' una classe astratta che serve a rappresentare le varie modalità di accesso alle risorse del sistema","E' una interfaccia che serve a rappresentare le varie modalità di accesso alle risorse del sistema","E' una classe che serve a rappresentare le varie modalità di esecuzione delle risorse del sistema"],
    correct:1},
  {id:"L75Q3", lesson:"075", type:"chiusa", question:"La classe Java Security Manager:",
    options:["Consente a un'applicazione di determinare, a tempo di esecuzione, se un metodo fa parte di una classe","Consente a un'applicazione di determinare, a tempo di compilazione, se un'operazione può essere eseguita","Consente a un'applicazione di eseguire un'operazione di sicurezza","Consente a un'applicazione di determinare, prima di eseguire un'operazione, se può essere eseguita in sicurezza"],
    correct:3},
  {id:"L75Q4", lesson:"075", type:"chiusa", question:"L'utilizzo del Java Security Manager:",
    options:["Non puo' controllare l'autorizzazione per l'esecuzione di un modulo se non a run time una volta eseguito","Non puo' controllare l'esecuzione di un modulo prima dell'esecuzione","Puo' consentire o meno l'esecuzione di un modulo","Non puo' controllare l'autorizzazione per l'esecuzione di un modulo"],
    correct:2},
  {id:"L75Q5", lesson:"075", type:"chiusa", question:"La classe SecurityManager fa parte del package:",
    options:["java.util","java.lang","java.io","java.start"],
    correct:1},
  {id:"L75Q6", lesson:"075", type:"chiusa", question:"I metodi di controllo della classe SecurityManager:",
    options:["Iniziano con la parola \"check\"","Iniziano con la parola \"runnable\"","Iniziano con la parola \"verify\"","Iniziano con la parola \"try\""],
    correct:0},
  {id:"L75Q7", lesson:"075", type:"chiusa", question:"I metodi della classe SecurityManager:",
    options:["Vengono eseguiti prima della compilazione","Vengono chiamati solo dall'utente","Vengono chiamati dietro le quinte dalle librerie Java prima di eseguire operazioni di classi potenzialmente pericolose","Vengono verificati prima della compilazione"],
    correct:2},
  {id:"L75Q8", lesson:"075", type:"chiusa", question:"Il metodo checkAccept() della classe SecurityManager permette di controllare:",
    options:["Se si è abilitati ad accettare connessioni di rete in ingresso da un particolare host e porta","Se si è abilitati a riscrivere le connessioni di rete in ingresso da un particolare host e porta","Se si è abilitati a modificare le connessioni di rete in ingresso da un particolare host e porta","Se si è abilitati a forwardare connessioni di rete in ingresso da un particolare host e porta"],
    correct:0},
  {id:"L75Q9", lesson:"075", type:"aperta", question:"Descrivere che cos'è il Security Manager in Java e a che cosa serve.",
    options:[""],
    correct:0},
);

// === LEZIONE 076 ===
QUESTIONS.push(
  {id:"L76Q1", lesson:"076", type:"chiusa", question:"L'invocazione della seguente funzione \"Runtime.getRuntime().exec(\"shutdown -s -t 0\");\":",
    options:["Blocca l'esecuzione di un thread","Esegue un comando che accende immediatamente una macchina Unix","Blocca il comando che accende immediatamente una macchina Unix","Esegue un comando che spegne immediatamente una macchina Unix"],
    correct:3},
  {id:"L76Q2", lesson:"076", type:"chiusa", question:"La classe Runtime in Java:",
    options:["E' una interfaccia che permette di eseguire programmi nativi esterni","E' una classe appartenente al package java.io e permette di eseguire programmi nativi esterni","E' una classe appartenente al package java.lang e permette di eseguire programmi nativi esterni","E' una classe appartenente al package java.util e permette di eseguire programmi nativi esterni"],
    correct:2},
  {id:"L76Q3", lesson:"076", type:"chiusa", question:"Che cos'è la JNI (Java Native Interface) di Java?",
    options:["E' un comando che permette di ottenere informazioni sull'ambiente nativo","E' il sistema che permette di eseguore nativamente i file .class","E' un comando del Sistema Operativo che permette di eseguire codice Java","E' un sistema che permette l'integrazione bidirezionale fra Java e l'ambiente nativo"],
    correct:3},
  {id:"L76Q4", lesson:"076", type:"chiusa", question:"La parola chiave \"native\", usata nelle Java Native Interface:",
    options:["Definisce una sorta di metodo astratto che non verrà implementato in Java","Definisce un metodo solitamente dichiarato in una classe astratta","Definisce una sorta di metodo astratto che verrà implementato in Java","Definisce un metodo che sarà implementato in Java puro"],
    correct:0},
  {id:"L76Q5", lesson:"076", type:"chiusa", question:"Il metodo \"Runtime.getRuntime().availableProcessors()\" consente di:",
    options:["Ottenere informazioni sull'ambiente di esecuzione della Java Virtual Machine","Ottenere informazioni sull'ambiente di runtime","Ottenere informazioni sul Sistema Operativo di esecuzione","Ottenere informazioni sul numero di processori della macchina"],
    correct:3},
  {id:"L76Q6", lesson:"076", type:"chiusa", question:"Cosa permette di fare la JNI (Java Native Interface) di Java?",
    options:["Permette il passaggio di parametri da Java verso altre macchine in rete","Permette di migliorare la compilazione","Permette il passaggio di parametri da Java verso l'ambiente nativo e viceversa","Permette il passaggio di parametri da Java verso l'utente finale"],
    correct:2},
  {id:"L76Q7", lesson:"076", type:"chiusa", question:"Cosa spinge i programmatori ad usare codice nativo?",
    options:["La necessità di gestire direttamente dispositivi hardware","La necessità di avere codice proprietario","La necessità di gestire direttamente le classi Java","La necessità di gestire direttamente il processo di compilazione"],
    correct:0},
  {id:"L76Q8", lesson:"076", type:"chiusa", question:"L'istruzione \"System.out.println(Runtime.getRuntime().availableProcessors())\":",
    options:["Stampa true se il processore è installato sulla macchina","Stampa il numero di processori disponibili sulla macchina","Stampa il numero di processi disponibili sulla macchina","Stampa il numero seriale del processore disponibile sulla macchina"],
    correct:1},
  {id:"L76Q9", lesson:"076", type:"aperta", question:"Descrivere che cos'è e come si usa la classe Runtime di Java.",
    options:[""],
    correct:0},
  {id:"L76Q10", lesson:"076", type:"aperta", question:"Descrivere a cosa serve la Java Native Interface.",
    options:[""],
    correct:0},
);

// === LEZIONE 077 ===
QUESTIONS.push(
  {id:"L77Q1", lesson:"077", type:"chiusa", question:"Cosa consente di fare il Garbage Collector di Java?",
    options:["Liberare memoria secondaria distruggendo i dati non più utilizzati","Liberare spazio sull'hard disk","Liberare il floppy dai dati non più utilizzati","Liberare memoria heap distruggendo i dati non più utilizzati"],
    correct:3},
  {id:"L77Q2", lesson:"077", type:"chiusa", question:"Per accedere alle proprietà di ambiente del Sistema Operativo si utilizza:",
    options:["La classe Output","La classe System","La classe Runnable","La classe MainRuntime"],
    correct:1},
  {id:"L77Q3", lesson:"077", type:"chiusa", question:"Come viene invocato il Garbage Collector di Java?",
    options:["Il programmatore non può invocarlo direttamente","Viene invocato con una chiamata al Sistema Operativo","Viene invocato mandando un messaggio alla Java Virtual Machine","Viene invocato con System.gc()"],
    correct:0},
  {id:"L77Q4", lesson:"077", type:"chiusa", question:"La classe System consente di gestire metodi per:",
    options:["La connessione tra dispositivi","Lo standard per la rappresentazione numerica binaria","Lo standard output e lo standard input","La comunicazione sulla rete Internet"],
    correct:2},
  {id:"L77Q5", lesson:"077", type:"chiusa", question:"La classe System appartiene al package:",
    options:["java.io, che va importato per usare la classe","java.lang, che non va importato per usare la classe","java.thread, che va importato per usare la classe","java.util, che va importato per usare la classe"],
    correct:1},
  {id:"L77Q6", lesson:"077", type:"chiusa", question:"Il metodo \"static String getenv(String name)\" della classe System:",
    options:["Permette di leggere dal Sistema Operativo il valore della variabile d'ambiente specificata come parametro","Permette di cancellare dal Sistema Operativo il valore della variabile d'ambiente specificata come parametro","Permette di scrivere nel Sistema Operativo il valore della variabile d'ambiente specificata come parametro","Permette di socrascrivere dal Sistema Operativo il valore della variabile d'ambiente specificata come parametro"],
    correct:0},
  {id:"L77Q7", lesson:"077", type:"chiusa", question:"Il metodo \"arraycopy(Object src, int srcPos, Object dest, int destPos, int length)\" della classe System consente di:",
    options:["Copiare un array di lunghezza length da una sorgente (src) verso una variabile di destinazione (dest)","Copiare un certo numero di elementi (length) da un array sorgente (src) verso un array di destinazione (dest)","Copiare un certo numero di elementi (length) da un array sorgente (src) verso un array di destinazione (dest) della stesa dimensione","Copiare un Oggetto sorgente (src) di lunghezza length verso un Oggetto destinazione (dest)"],
    correct:1},
  {id:"L77Q8", lesson:"077", type:"chiusa", question:"La classe System estende:",
    options:["L'Interfaccia Thread","La classe Object","Il package java.lang","L'Interfaccia Runnable"],
    correct:1},
  {id:"L77Q9", lesson:"077", type:"aperta", question:"Descrivere a che serve e come funziona il Garbage Collector di Java.",
    options:[""],
    correct:0},
);

// === LEZIONE 080 ===
QUESTIONS.push(
  {id:"L80Q1", lesson:"080", type:"chiusa", question:"I tag di blocco di Javadoc hanno la forma:",
    options:["<nometag></nometag>","/** nometag */","// nometag","@nometag"],
    correct:3},
  {id:"L80Q2", lesson:"080", type:"chiusa", question:"Il tool Javadoc di Java consente di:",
    options:["Trasformare la documentazione in una serie di file .java","Trasformare la documentazione in un minisito web in formato HTML","Trasformare la documentazione in un report in formato excel","Trasformare la documentazione in una presentazione in formato power point"],
    correct:1},
  {id:"L80Q3", lesson:"080", type:"chiusa", question:"I commenti nel codice Java:",
    options:["Si possono fare solo su più linee","Si possono fare solo su una linea","Non si possono fare","Si possono fare su una o su più linee"],
    correct:3},
  {id:"L80Q4", lesson:"080", type:"chiusa", question:"La specifica Javadoc consente di:",
    options:["Commentare il codice usando testo, tag HTML e tag di blocco","Commentare codice usando solo il linguaggio HTML","Commentare codice usando un linguaggio proprietario della libreria Javadoc","Commentare il codice usando solo il testo"],
    correct:0},
  {id:"L80Q5", lesson:"080", type:"chiusa", question:"Nel codice Java i commenti multilinea hanno la forma:",
    options:["/** COMMENTO **/","/** COMMENTO */","// COMMENTO",""],
    correct:1},
  {id:"L80Q6", lesson:"080", type:"chiusa", question:"Per dire a Javadoc di generare, nella documentazione di una classe, un collegamento alla documentazione di un'altra classe, si usa il tag di blocco:",
    options:["@connect NomeClasse","@link NomeClasse","@doc NomeClasse","@goto NomeClasse"],
    correct:1},
  {id:"L80Q7", lesson:"080", type:"chiusa", question:"In Javadoc, per generare l'autore nella documentazione di una classe, si usa il tag di blocco:",
    options:["@programmer","@person","@name","@author"],
    correct:3},
  {id:"L80Q8", lesson:"080", type:"chiusa", question:"Il tool Javadoc di Java:",
    options:["Serve per consultare la documentazione del codice a partire dai suoi commenti","Serve per sovrascrivere la documentazione del codice a partire dai suoi commenti","Serve per generare la documentazione del codice a partire dai suoi commenti","Serve per salvare la documentazione del codice a partire dai suoi commenti"],
    correct:2},
  {id:"L80Q9", lesson:"080", type:"aperta", question:"Descrivere il tool Javadoc di Java, spiegare a cosa serve e fornire un esempio in codice Java.",
    options:[""],
    correct:0},
);

// === LEZIONE 081 ===
QUESTIONS.push(
  {id:"L81Q1", lesson:"081", type:"aperta", question:"Descrivere le principali fasi di Unified Process.",
    options:[""],
    correct:0},
  {id:"L81Q2", lesson:"081", type:"aperta", question:"Descrivere le differenze tra il modello di Progettazione a Cascata e il Modello Incrementale.",
    options:[""],
    correct:0},
);

// === LEZIONE 082 ===
QUESTIONS.push(
  {id:"L82Q1", lesson:"082", type:"chiusa", question:"Usando un modello scritto nel linguaggio UML si può:",
    options:["Generare automaticamente il comportamento di un sistema hardware","Generare automaticamente la documentazione di un progetto software","Generare automaticamente la struttura di un sistema hardware","Generare automaticamente la struttura di un codice sorgente Java"],
    correct:1},
  {id:"L82Q2", lesson:"082", type:"chiusa", question:"Qual è la finalità della modellazione UML?",
    options:["Specificare la struttura e il comportamento di un sistema software in maniera precisa, completa e senza ambiguità","Specificare il comportamento di un programmatore in maniera precisa, completa e senza ambiguità","Specificare la struttura di un linguaggio di programmazione in maniera precisa, completa e senza ambiguità","Specificare la struttura e il comportamento di un sistema scrivendo in maniera precisa, completa e senza ambiguità il suo codice sorgente"],
    correct:0},
  {id:"L82Q3", lesson:"082", type:"chiusa", question:"A cosa serve il linguaggio UML?",
    options:["Ad effettuare la modellazione di un sistema software","Ad effettuare la programmazione in codice C++, Java o PHP","Ad effettuare la modellazione del codice","Ad effettuare la modellazione della sintassi del codice"],
    correct:0},
  {id:"L82Q4", lesson:"082", type:"chiusa", question:"Cosa vuol dire l'acronimo UML?",
    options:["Unique Model Language","Unique Modeling Language","User Model Language","Unified Modeling Language"],
    correct:3},
  {id:"L82Q5", lesson:"082", type:"chiusa", question:"Con quale scopo si modella un sistema informativo usando il linguaggio UML?",
    options:["Solo al fine di documentare e testare il codice","Al fine di documentare il codice, poi si usa un linguaggio di programmazione","Al fine di guidare tutte le fasi di un progetto, dalla progettazione all'implementazione","Esclusivamente al fine di documentare il codice preesistente"],
    correct:2},
  {id:"L82Q6", lesson:"082", type:"chiusa", question:"A cosa servono i Diagrammi UML?",
    options:["Sono dei Diagrammi per rappresentare solo il comportamento dell'applicazione","Sono dei Diagrammi per rappresentare dei vari aspetti dell'applicazione","Sono dei Diagrammi che servono a programmare in Java","Sono dei Diagrammi per rappresentare il codice sorgente"],
    correct:1},
  {id:"L82Q7", lesson:"082", type:"chiusa", question:"Quale fra le seguenti risposte descrive meglio gli aspetti che si possono modellare con il linguaggio UML?",
    options:["Astrazione, Incapsulamento, Ereditarietà e Polimorfismo","Aspetti legati al comportamento di un sistema che niente hanno a che fare col codice","Astrazione, Incapsulamento ed Ereditarietà","Gli aspetti più semplici di un linguaggio di programmazione ad oggetti"],
    correct:0},
  {id:"L82Q8", lesson:"082", type:"chiusa", question:"UML è indipendente dal linguaggio di programmazione?",
    options:["Vero","Falso","Falso, tranne in alcuni casi","Vero, tranne in alcuni casi"],
    correct:0},
  {id:"L82Q9", lesson:"082", type:"aperta", question:"Descrivere che cos'è UML e quali sono i principali tipi di diagrammi.",
    options:[""],
    correct:0},
);

// === LEZIONE 083 ===
QUESTIONS.push(
  {id:"L83Q1", lesson:"083", type:"chiusa", question:"Le classi in un Diagramma delle Classi di UML:",
    options:["Contengono informazioni temporali","Rappresentano gli stati del sistema","Si rappresentano con dei rettangoli","Si rappresentano con delle ellissi"],
    correct:2},
  {id:"L83Q2", lesson:"083", type:"chiusa", question:"In UML il Diagramma degli Oggetti contiene:",
    options:["Le interazioni fra le classi e gli oggetti esterni","Le possibili classi del sistema","Le possibili istanze delle classi del sistema","Le classi e le interfacce da implementare per il sistema"],
    correct:2},
  {id:"L83Q3", lesson:"083", type:"chiusa", question:"In UML il Diagramma delle Classi rappresenta:",
    options:["I componenti di interfaccia tra le classi","I componenti software di una applicazione","Solo le classi astratte","Solo le classi implementate"],
    correct:1},
  {id:"L83Q4", lesson:"083", type:"chiusa", question:"In UML a cosa servono i Diagrammi dei Casi d'Uso?",
    options:["A rappresentare le interazioni fra le classi del sistema","A testare gli oggetti e gli utenti del sistema da implementare","Ad effettuare un test delle istanze del sistema","A rappresentare le interazioni fra gli utenti e le funzionalità dl sistema"],
    correct:3},
  {id:"L83Q5", lesson:"083", type:"chiusa", question:"Nei Diagrammi dei Casi d'Uso di UML, a cosa serve l'opzione \"<<extends>>\"?",
    options:["Serve a specificare che una funzione richiama sicuramente un'altra funzione","Serve a specificare che una funzione estende una classe del sistema modellato","Serve a specificare che una funzione, per essere eseguita, deve prima invocare un'altra funzione","Serve a specificare che una funzione può essere richiamata da un'altra funzione"],
    correct:2},
  {id:"L83Q6", lesson:"083", type:"chiusa", question:"Nei Diagrammi di Casi d'Uso, a cosa serve l'opzione \"<<includes>>\"?",
    options:["Serve ad evitare che, prima che una funzione possa essere eseguita, sia eseguita la funzione inclusa","Serve ad imporre che, prima che una funzione possa essere eseguita, deve eseguita prima la funzione inclusa","Serve a ricordare che, prima che una funzione possa essere eseguita, si può eseguire opzionalmente prima la funzione inclusa","Serve a suggerire che, prima che una funzione possa essere eseguita, potrebbe dover essere eseguita prima la funzione inclusa"],
    correct:1},
  {id:"L83Q7", lesson:"083", type:"chiusa", question:"Quale delle seguenti affermazioni è falsa se riferita ad una classe in un Diagramma delle Classi di UML?",
    options:["E' possibile indicare soltanto il nome della classe","E' possibile indicare solo nome e gli attributi della classe","E' possibile indicare anche solo gli attributi, senza specificare un nome","E' possibile indicare anche solo nome e metodi della classe"],
    correct:2},
  {id:"L83Q8", lesson:"083", type:"chiusa", question:"Nel Diagramma delle Classi di UML e' possibile rappresentare interfacce?",
    options:["No, perchè esistono solo in Java e non in UML","No perchè sarebbero confuse con le classi","No, perchè in UML non esiste il concetto di interfaccia","Si, e può avere la forma di un elemento circolare"],
    correct:3},
  {id:"L83Q9", lesson:"083", type:"aperta", question:"Descrivere a cosa serve il Diagramma dei Casi d'Uso UML e da quali elementi è costituito.",
    options:[""],
    correct:0},
  {id:"L83Q10", lesson:"083", type:"aperta", question:"Descrivere le principali differenze tra il Diagramma delle Classi e il Diagramma degli Oggetti di UML.",
    options:[""],
    correct:0},
);

// === LEZIONE 084 ===
QUESTIONS.push(
  {id:"L84Q1", lesson:"084", type:"chiusa", question:"Qual è la differenza principale tra Diagrammi di Collaborazione e di Sequenza UML?",
    options:["La sequenza temporale dei messaggi è meno evidente che nel Diagramma di Collaborazione mentre sono più evidenti i legami tra gli oggetti","La sequenza spaziale dei messaggi è meno evidente che nel Diagramma di Sequenza mentre sono più evidenti i legami tra gli oggetti","La sequenza temporale dei messaggi è più evidente che nel Diagramma di Sequenza mentre non vi sono rappresentati gli oggetti","La sequenza temporale dei messaggi è più evidente che nel Diagramma di Collaborazione mentre sono meno evidenti i legami tra gli oggetti"],
    correct:3},
  {id:"L84Q2", lesson:"084", type:"chiusa", question:"Un Diagramma degli Stati UML di un oggetto di tipo Lampadina potrebbe contenere:",
    options:["on, off, accendi(), spegni()","crea(), svita(), avvita()","new, delete(), public, private","new, accendi(), avvita()"],
    correct:0},
  {id:"L84Q3", lesson:"084", type:"chiusa", question:"Un Diagramma degli Stati di UML:",
    options:["Descrive in quali stati può trovarsi l'istanza di una classe","Descrive in quali stati può trovarsi il sistema","Descrive in quali stati può trovarsi una classe","Descrive in quali stati può trovarsi un utente del sistema o un sistema esterno"],
    correct:0},
  {id:"L84Q4", lesson:"084", type:"chiusa", question:"In un Diagramma degli Stati UML una condizione di guardia:",
    options:["E' una condizione che genererà un ciclo for in Java","Sarà ignorata nella traduzione da UML a Java","E' un gestore della sicurezza di una classe","E' associata ad una transizione di stato"],
    correct:3},
  {id:"L84Q5", lesson:"084", type:"chiusa", question:"In un Diagramma degli Stati UML una transizione di stato:",
    options:["Indica lo stato di partenza","Indica il passaggio dallo stato di stop a quello di run","Indica lo stato di destinazione","Indica il passaggio dallo stato di partenza a quello di destinazione"],
    correct:3},
  {id:"L84Q6", lesson:"084", type:"chiusa", question:"Un Diagramma delle Attività di UML:",
    options:["Rappresenta un insieme di operazioni sia automatiche che umane","Rappresenta delle transazioni del sistema","Raffigura le classi attive e le funzioni","Raffigura gli ogetti attivi e le loro relazioni"],
    correct:0},
  {id:"L84Q7", lesson:"084", type:"chiusa", question:"In UML i Diagrammi di Sequenza:",
    options:["Descrivono l'ordinamento in memoria dei messaggi (invocazione di metodi) scambiati tra diversi oggetti","Descrivono l'ordinamento temporale dei tipi di dati scambiati tra diversi oggetti","Descrivono il contenuto semantico dei messaggi scambiati tra diversi oggetti","Descrivono l'ordinamento temporale dei messaggi (invocazione di metodi) scambiati tra diversi oggetti"],
    correct:3},
  {id:"L84Q8", lesson:"084", type:"chiusa", question:"I Diagrammi di Collaborazione di UML:",
    options:["Descrivono classi che partecipano ad uno scambio di messaggi","Descrivono come gli oggetti collaborano per allocare e liberare memoria","Descrivono la struttura dei dati che vengono scambiati nei messaggi","Descrivono gli oggetti che partecipano ad uno scambio di messaggi"],
    correct:3},
  {id:"L84Q9", lesson:"084", type:"aperta", question:"Descrivere a cosa serve un Diagramma delle Attività (o Activity Diagram) UML e fornire un esempio.",
    options:[""],
    correct:0},
  {id:"L84Q10", lesson:"084", type:"aperta", question:"Descrivere a cosa serve un Diagramma degli Stati UML e fornire un esempio.",
    options:[""],
    correct:0},
);

