// === LEZIONE 035 - Ricorsione ===
QUESTIONS.push(
  {id:"L35Q1", lesson:"035", type:"chiusa", question:"La tecnica di programmazione ricorsiva:",
    options:["Si basa sulla tecnica di induzione","Si basa sulla tecnica di programmazione dinamica","Si basa sulla programmazione iterativa","Si basa su metodi euristici"],
    correct:0},
  {id:"L35Q2", lesson:"035", type:"chiusa", question:"Dato un algoritmo matematicamente ricorsivo si dice che:",
    options:["Non è possibile stabilire se la sua implementazione iterativa sia sempre migliore di quella ricorsiva","Non si può mai definire una implementazione iterativa","E' sempre possibile indicare una implementazione iterativa ma mai ricorsiva","Si può definire sempre e solo una implementazione ricorsiva"],
    correct:0},
  {id:"L35Q3", lesson:"035", type:"chiusa", question:"Dovendo implementare in Java l'algoritmo di calcolo del fattoriale di un numero contenuto in una variabile 'n', quale fra queste linee di codice posso utilizzare?",
    options:["La linea di codice 'return n * fact(n-1)'","La linea di codice 'return (n+1)*fact(n+1)'","La linea di codice 'return fact(n)*fact(n)'","La linea di codice 'return fact(n+1)'"],
    correct:0},
  {id:"L35Q4", lesson:"035", type:"chiusa", question:"Quale di queste affermazioni è falsa:",
    options:["La tecnica di ricorsione si usa ad esempio per il calcolo del numero di fibonacci","La tecnica di ricorsione si può solo usare se contiene cicli (for o while)","La tecnica di ricorsione è una funzione che contiene il nome della funzione al suo interno","La tecnica di ricorsione si usa ad esempio per il calcolo del fattoriale di un numero"],
    correct:1},
  {id:"L35Q5", lesson:"035", type:"chiusa", question:"Data una funzione recursive(), quale delle seguenti affermazioni è certamente corretta?",
    options:["La funzione recursive() è ricorsiva perché fa parte delle librerie Java","La funzione deve avere nel suo blocco di codice l'istruzione 'recursive()' per definirsi ricorsiva","La funzione deve includere sempre un ciclo di while per esser ricorsiva","La funzione deve contenere una invocazione ricorsiva in un ciclo"],
    correct:1},
  {id:"L35Q6", lesson:"035", type:"chiusa", question:"Il calcolo del fattoriale di un numero intero si può:",
    options:["Calcolare solo con metodo ricorsivo","Calcolare solo con l'ausilio del calcolo parallelo","Calcolare solo con un ciclo di for","Calcolare sia con la tecnica ricorsiva che tramite l'uso di cicli"],
    correct:3},
  {id:"L35Q7", lesson:"035", type:"chiusa", question:"La tecnica ricorsiva consente di invocare una stessa funzione dall'interno del codice in quanto:",
    options:["Usa lo Stack di attivazione","Usa il calcolo parallelo","Usa il disco rigido","Usa la memoria a nastro"],
    correct:0},
  {id:"L35Q8", lesson:"035", type:"chiusa", question:"La Ricorsione è una tecnica di programmazione che:",
    options:["Si utilizza quando è necessario ripetere delle azioni in modo ottimale","Si basa sulla rincorsa del codice","Si utilizza solo per analizzare numeri interi","Si basa sulla invocazione di una stessa funzione dall'interno della funzione stessa"],
    correct:3},
);

// === LEZIONE 036 - String ===
QUESTIONS.push(
  {id:"L36Q1", lesson:"036", type:"chiusa", question:"Per aggiungere una stringa ad un'altra stringa in una variabile si usa:",
    options:["Il metodo 'string.appendMeOnline()'","Il metodo 'StringBuffer.append(char[] c)'","Il metodo 'Char.AggangiaStringa()'","Il metodo 'String.Append(s1, s2)'"],
    correct:1},
  {id:"L36Q2", lesson:"036", type:"chiusa", question:"Data la funzione 'StringBuffer insert(int offset, long l)' consente di:",
    options:["Inserire un nuovo valore di offset su una stringa s","Cancellare una stringa di lunghezza l da un una posizione 'offset'","Inserire la rappresentazione stringa dell'argomento long nella sequenza di caratteri","Stampare a video una parola inserita in una stringa"],
    correct:2},
  {id:"L36Q3", lesson:"036", type:"chiusa", question:"Data una variabile sb di tipo StringBuffer, con valore: sb = 'Prova '; la funzione sb.append('test'):",
    options:["Appende uno spazio vuoto alla fine di sb (risultato sb = 'Prova ')","Appende un carattere alla variabile sb (risultato sb = 'Prova t')","Appende un testo alla variabile sb (risultato sb = 'Prova test')","Appende la parola append alla variabile sb (risultato sb = 'Prova append')"],
    correct:2},
  {id:"L36Q4", lesson:"036", type:"chiusa", question:"Data l'istruzione: String s = new String('test'); la variabile s consente di:",
    options:["Definire un insieme di caratteri stampabili singolarmente","Memorizzare solo bytecode","Memorizzare in s valori numerici","Stampare il contenuto della variabile s"],
    correct:0},
  {id:"L36Q5", lesson:"036", type:"chiusa", question:"Se serve per una stringa manipolare i singoli caratteri è necessario:",
    options:["Si usa un array di caratteri della forma char[]","Si usa una tecnica di mappaggio delle stringhe in interi","Non si può implementare mai in Java","Si definisce una funzione dedicata che usi i double"],
    correct:0},
  {id:"L36Q6", lesson:"036", type:"chiusa", question:"Data l'istruzione: String saluto = 'Ciao a tutti'; quale di queste affermazioni è vera:",
    options:["Non si possono modificare i singoli caratteri della variabile 'saluto'","Si possono invertire o saltare i caratteri dalle stringa 'saluto'","Non si può stampare la stringa 'saluto'","Si possono cambiare i caratteri della stringa 'saluto'"],
    correct:0},
  {id:"L36Q7", lesson:"036", type:"chiusa", question:"In Java le stringhe si definiscono utilizzando:",
    options:["La classe CharacaterString()","Le funzioni char()","Le matrici definite dagli utenti","La classe statica definita nella libreria di Java di nome String"],
    correct:3},
  {id:"L36Q8", lesson:"036", type:"chiusa", question:"Quale di queste affermazioni è sicuramente falsa?",
    options:["Una istanza di una variabile char è stampabile a video","Una istanza di stringa String() è stampabile a video","Una istanza della classe String e un array di char sono esattamente uguali","I caratteri in una istanza di String sono immutabili"],
    correct:2},
);

// === LEZIONE 037 - String Methods ===
QUESTIONS.push(
  {id:"L37Q1", lesson:"037", type:"chiusa", question:"Le due operazioni: 1) String s = new String(); e 2) String s = '';",
    options:["Sono differenti e costruiscono una stringa s con valori nulli e una stringa s senza caratteri","Sono equivalenti e costruisono una stringa con 10 caratteri vuoti","Sono equivalenti e costruiscono una stringa vuota","Sono differenti e costruiscono una stringa s senza caratteri e una stringa s con valori nulli"],
    correct:2},
  {id:"L37Q2", lesson:"037", type:"chiusa", question:"Date le due istruzioni Java in sequenza: 'char[] c = {'t', 'e', 's', 't'};' e 'String s = new String(c);'",
    options:["Crea una stringa s che contiene il primo carattere 't' della variabile c","Crea una stringa s che contiene la parola ''t''e''s''t''","Crea una nuova stringa s che non contiene nulla","Crea una stringa s che contiene la parola 'test'"],
    correct:3},
  {id:"L37Q3", lesson:"037", type:"chiusa", question:"Data una stringa s = new String('prova');, per stampare la lettera 'o' si procede con:",
    options:["System.out.println([2]);","System.out.println([II]);","System.out.println(s.charAt(2));","System.out.println(s.2);"],
    correct:2},
  {id:"L37Q4", lesson:"037", type:"chiusa", question:"Per confrontare due stringhe s1 ed s2 e verificare se hanno lo stesso valore si procede con:",
    options:["L'istruzione Java 'if (s1=s2)'","L'istruzione Java 'if (Equals(s1,s2))'","L'istruzione Java 'if (s1==s2)'","L'istruzione Java 'if (s1.equals(s2))'"],
    correct:3},
  {id:"L37Q5", lesson:"037", type:"chiusa", question:"Data una stringa s generata in Java come: s = new String('prova');, quale delle seguenti affermazioni è falsa?",
    options:["s2=s.substring(1,3) inserisce in s2 la stringa 'rov'","s2=s.substring(1,3) inserisce in s2 la stringa intera","s2=s.substring(1,3) serve a copiare una parte di s in s2","s2=s.substring(1,3) si usa per generare una sottostringa di s"],
    correct:1},
  {id:"L37Q6", lesson:"037", type:"chiusa", question:"La funzione 'String concat(String s)':",
    options:["E' una funzione della classe String che serve a concatenare una stringa data con la stringa parametro s","E' una funzione che serve a concatenare sue stringhe date in input e mette in risultato nel parametro s","E' una procedura della classe String che serve a stampare la stringa s concatenata con se stessa","E' una funzione che serve a comunicare una stringa s a una funzione di stampa"],
    correct:0},
  {id:"L37Q7", lesson:"037", type:"chiusa", question:"Data il seguente codice: String s1 = new String('stringa'); String s2 = new String(' di prova'); quale delle seguenti affermazioni è vera?",
    options:["System.out.println(s1.concat(s2)) stampa 'stringa di prova'","System.out.println(s1.concat(s2)) stampa ' prova di stringa'","System.out.println(s1.concat(s2)) stampa ' prova'","System.out.println(s1.concat(s2)) stampa ' stringa'"],
    correct:0},
  {id:"L37Q8", lesson:"037", type:"chiusa", question:"A cosa serve la classe StringTokenizer?",
    options:["Serve ad estrarre token da una stringa","Serve a gestire una sequenza di stringhe come interi","Serve a fare dei cicli sulle stringhe","Serve a generare token casuali usando le stringhe"],
    correct:0},
);

// === LEZIONE 038 - Keywords ===
QUESTIONS.push(
  {id:"L38Q1", lesson:"038", type:"chiusa", question:"La parola chiave 'import' indica:",
    options:["Un modo per dire che una istruzione è importante","Un modo per escludere alcune classi","Un modo per includere le funzionalità di una classe","Un modo per indicare l'importazione di variabili"],
    correct:2},
  {id:"L38Q2", lesson:"038", type:"chiusa", question:"La parola chiave protected si può usare:",
    options:["Nella definizione dei package per cui chiedo protezione","Nella definizione dei metodi di una classe","Per le funzioni invocabili solo con sistema operativo","Nella definizione di codice antihacker"],
    correct:1},
  {id:"L38Q3", lesson:"038", type:"chiusa", question:"Quali di queste affermazioni è sicuramente falsa?",
    options:["La parola chiave 'long' è un intero con segno","La parola chiave 'long' indica un tipo","La parola chiave 'long' si usa per i valori numerici","La parola chiave 'long' serve a definire stringhe più lunghe"],
    correct:3},
  {id:"L38Q4", lesson:"038", type:"chiusa", question:"La parola chiave package:",
    options:["Indica la versione dei pacchetti generati dall'utente","Indica la versione della CPU","Indica la versione del compilatore di Java","Indica un pacchetto o libreria di funzioni"],
    correct:3},
  {id:"L38Q5", lesson:"038", type:"chiusa", question:"La parola chiave instanceof si utilizza per:",
    options:["Testare se un programma è istanziato","Testare se un programma è in esecuzione","Testare se una variabile e istanziabile","Testare se una variabile è una istanza di un certo tipo"],
    correct:3},
  {id:"L38Q6", lesson:"038", type:"chiusa", question:"Data l'istruzione: String final = 'fine'; che succede se la compiliamo?",
    options:["Genera un errore perchè final è una parola chiave","Genera un errore perchè una stringa non si definisce così","Non genera alcun errore","Genera un errore perchè dopo l'uguale non ci vogliono mai le virgolette"],
    correct:0},
  {id:"L38Q7", lesson:"038", type:"chiusa", question:"Quali delle seguenti parole non è una parola chiave di Java?",
    options:["Class","abstract","else","boolean"],
    correct:-1}, // Tutte sono keywords, la domanda sembra errata nel PDF
  {id:"L38Q8", lesson:"038", type:"chiusa", question:"Per invocare un metodo di una classe padre nella gerarchia di classi Java si usa la parola chiave:",
    options:["super","ancestor","ancien","overthetop"],
    correct:0},
);

// === LEZIONE 039 - Objects and Classes ===
QUESTIONS.push(
  {id:"L39Q1", lesson:"039", type:"chiusa", question:"Data la classe 'Persona', la seguente istruzione 'Persona p1 = new Persona();' serve a:",
    options:["Creare un oggetto p1 che sia di tipo Persona","Inizializzare la classe Persona","Creare una nuova classe p1 di tipo Persona","Creare una variabile p1 che contenga un array di persone"],
    correct:0},
  {id:"L39Q2", lesson:"039", type:"chiusa", question:"L'istruzione new serve a:",
    options:["Creare un nuovo programma Java","Istanziare un nuovo sistema operativo","Istanziare una nuova funzione","Istanziare un nuovo oggetto di una classe"],
    correct:3},
  {id:"L39Q3", lesson:"039", type:"chiusa", question:"Data la classe 'public class Persona { String nome; }' e una sua istanza p1, quali delle seguenti istruzioni è corretta:",
    options:["System.out.println(nome);","System.out.println(p1->nome);","System.out.println(p1.nome);","System.out.println(p1);"],
    correct:2},
  {id:"L39Q4", lesson:"039", type:"chiusa", question:"Per ottenere una nuova istanza di una classe non statica è necessario:",
    options:["Allocare la memoria con una istruzione di new","Invocare e allocare la classe","Allocare la classe","Definire la classe"],
    correct:0},
  {id:"L39Q5", lesson:"039", type:"chiusa", question:"Data una classe quante istanze di oggetti si possono creare?",
    options:["Fino a un massimo di 10","Soltanto due","Un numero illimitato","Un numero limitato"],
    correct:2},
  {id:"L39Q6", lesson:"039", type:"chiusa", question:"Il codice sorgente Java che definisce una classe di nome 'Prova' in quale file deve essere salvato?",
    options:["Prova.exe","Prova.class","Un file di testo qualsiasi","Prova.java"],
    correct:3},
  {id:"L39Q7", lesson:"039", type:"chiusa", question:"Dato un insieme di classi java è conveniente:",
    options:["Salvare tutto in un file.doc","Salvare ogni classe in un file nomeclasse.java","Salvare ogni classe in un file estensione '.txt'","Salvare ogni classe in una cartella senza estensione"],
    correct:1},
  {id:"L39Q8", lesson:"039", type:"chiusa", question:"Per accedere alla variabile di istanza 'n' della classe 'NomeClasse' si usa:",
    options:["n.NomeClasse.GetClassVariable","NomeClasse.n","n.NomeClasse","NomeClasse.GetName('n')"],
    correct:-1}, // Nessuna risposta corretta nel PDF
);

// === LEZIONE 040 - Static Methods ===
QUESTIONS.push(
  {id:"L40Q1", lesson:"040", type:"chiusa", question:"E' possibile definire dei metodi statici di classe:",
    options:["L'utente non può mai farlo","Inserendo il punto prima del metodo","Inserendo la parola NoDynamic prima del metodo","Inserendo il nome static prima del metodo"],
    correct:3},
  {id:"L40Q2", lesson:"040", type:"chiusa", question:"Data la classe Math che fa parte del package java.lang, la funzione sqrt(double a):",
    options:["Esegue il quadrato del valore nella variabile 'a'","Esegue la radice cubica del valore nella variabile 'a'","Arrotonda il valore del numero a virgola mobile di 'a'","Esegue la radice quadrata del valore nella variabile 'a'"],
    correct:3},
  {id:"L40Q3", lesson:"040", type:"chiusa", question:"Un metodo statico può essere:",
    options:["Invocato una sola volta","Non può mai esser invocato","Invocato senza definire un oggetto","Invocato senza programmazione dinamica"],
    correct:2},
  {id:"L40Q4", lesson:"040", type:"chiusa", question:"La funzione 'static double cos(double a)' della classe Math restituisce:",
    options:["Il valore doppio della variabile a","Il coseno della variabile a","True se la variabile a contiene un valore costante","L'arcoseno della variabile a"],
    correct:1},
  {id:"L40Q5", lesson:"040", type:"chiusa", question:"Data una classe ed un oggetto, l'operatore instanceof consente di:",
    options:["Sapere se la classe è statica","Sapere se l'oggetto è statico","Sapere se sia l'oggetto che la classe sono istanze statiche","Sapere se l'oggetto è istanza della classe"],
    correct:3},
  {id:"L40Q6", lesson:"040", type:"chiusa", question:"Dato il seguente codice Java: String s = new String('test'); if (s instanceof String), il risultato del test dell'if è:",
    options:["Non si può eseguire","false","true","'test'"],
    correct:2},
  {id:"L40Q7", lesson:"040", type:"chiusa", question:"La funzione 'static double abs(double a)' della classe Math restituisce:",
    options:["Il valore zero se a è pari","Il valore assoluto della variabile a","Il valore zero se a è dispari","La parte decimale del valore di a"],
    correct:1},
  {id:"L40Q8", lesson:"040", type:"chiusa", question:"Data la funzione Java: 'public void stampa() {System.out.println('Messaggio di prova');}', il metodo main 'public static void main(String[] args) {stampa();}' è:",
    options:["Errato in quanto la funzione richiede che venga creata una istanza della classe","Corretto in quanto il main viene sempre compilato","Errato perchè il main non può chiamare una funzione pubblica","Corretto in quanto la funzione non richiede che venga creata una istanza della classe"],
    correct:0},
);

// === LEZIONE 041 - Attributes and Methods ===
QUESTIONS.push(
  {id:"L41Q1", lesson:"041", type:"chiusa", question:"Data la seguente porzione di codice: 'Punto p = new Punto();', dove Punto è il nome di una classe, quale delle seguenti affermazioni è falsa?",
    options:["p è un metodo","p è una istanza di classe","p è una istanza e si può accedere alle sue variabili","p non è un metodo"],
    correct:0},
  {id:"L41Q2", lesson:"041", type:"chiusa", question:"In Java un attributo e un metodo:",
    options:["Sono sinonimi","Sono due cose diverse","Sono intercambiabili","Sono la stessa cosa"],
    correct:1},
  {id:"L41Q3", lesson:"041", type:"chiusa", question:"Dato il seguente spezzone di codice Java 'Punto p = new Punto();' se la classe Punto contiene due variabili accessibili x e y, allora:",
    options:["E' possibile accedere ad x e ad y usando p^x e p^y","E' possibile accedere ad x e ad y usando p->x e p->y","E' impossibile accedere ad x e y","E' possibile accedere ad x e ad y usando p.x e p.y"],
    correct:3},
  {id:"L41Q4", lesson:"041", type:"chiusa", question:"Quale delle seguenti affermazioni è corretta?",
    options:["Gli attributi di una classe sono metodi che si invocano dall'esterno","Gli attributi di una classe sono delle variabili che ne rappresentano lo stato","Gli attributi di una classe sono metodi che si invocano dall'interno","Gli attributi di una classe sono metodi ricorsivi"],
    correct:1},
  {id:"L41Q5", lesson:"041", type:"chiusa", question:"L'istruzione Java 'return Math.sqrt(x*x + y*y);' ritorna:",
    options:["La radice quadrata di x sommato ad y","Il quadrato di x","Il quadrato di x sommato ad y","La radice quadrata della somma dei quadrati di x e y"],
    correct:3},
  {id:"L41Q6", lesson:"041", type:"chiusa", question:"Data una classe di nome 'Punto' ed un metodo dichiarato come 'double getDistanza()':",
    options:["Il metodo non è invocabile","Il metodo si invoca attraverso il nome di una istanza di classe","Il metodo si invoca senza istanza di classe","Il metodo si invoca solo dall'interno della classe"],
    correct:1},
  {id:"L41Q7", lesson:"041", type:"chiusa", question:"In Java un attributo si definisce usando:",
    options:["Solo tipi definiti dagli utenti","Tipi interessanti","Tipi speciali","Tipi di base"],
    correct:3},
  {id:"L41Q8", lesson:"041", type:"chiusa", question:"In Java, dovendo dichiarare due variabili x e y, le due seguenti modalità: 1) 'double x, y;' e 2) 'double x; double y;':",
    options:["La modalità 1 è errata mentre la 2 è corretta","Sono entrambe errate","Sono equivalenti ma la prima modalità è sconsigliata","Sono due modalità diverse che hanno effetti differenti in memoria"],
    correct:2},
);

// === LEZIONE 042 - Constructors ===
QUESTIONS.push(
  {id:"L42Q1", lesson:"042", type:"chiusa", question:"In Java un costruttore di una classe:",
    options:["Ha lo stesso nome della classe","E' un oggetto che è obbligatorio definire","E' un sistema di costruzione degli attributi","Ha un metodo standard build"],
    correct:0},
  {id:"L42Q2", lesson:"042", type:"chiusa", question:"Se ci riferiamo ai costruttori, quale fra le seguenti affermazioni è falsa?",
    options:["In Java un costruttore di classe ha il nome della classe","In Java un costruttore di classe si invoca nella istruzione new","In Java un costruttore di classe è sempre presente","In Java un costruttore di classe può avere parametri"],
    correct:2},
  {id:"L42Q3", lesson:"042", type:"chiusa", question:"Data una classe Java è possibile:",
    options:["Avere un costruttore che ritorna un int","Avere più costruttori","Avere due costruttori con gli stessi parametri","Avere un costruttore che ritorna un valore booleano"],
    correct:1},
  {id:"L42Q4", lesson:"042", type:"chiusa", question:"In una classe Java due costruttori:",
    options:["Si distinguono per nome","Si distinguono per il tipo di ritorno","Si distinguono per i valori che ritornano","Si distinguono per numero di parametri passati alla funzione di costruzione"],
    correct:3},
  {id:"L42Q5", lesson:"042", type:"chiusa", question:"In un costruttore è possibile utilizzare il comando 'this' per:",
    options:["Riferirsi alle variabili esterne","Riferirsi ai link alle variabili e ai metodi","Riferirsi all'istanza corrente","Riferirsi agli oggetti che di collegano a questo oggetto"],
    correct:2},
  {id:"L42Q6", lesson:"042", type:"chiusa", question:"Si utilizzano più costruttori quando:",
    options:["Si vuole cambiare attributi velocemente","Si vuole avere più metodi di inizializzazione","Non si utilizzano mai","Si vuole istanziare più volte lo stesso oggetto"],
    correct:1},
  {id:"L42Q7", lesson:"042", type:"chiusa", question:"Se in una classe non è stato definito alcun costruttore:",
    options:["La classe non potrà essere compilata","Vuol dire che esiste solo il distruttore","E' considerato un errore","Non è un errore"],
    correct:3},
  {id:"L42Q8", lesson:"042", type:"chiusa", question:"In una classe Java 'Punto', il seguente metodo 'Punto() { this(0.0, 0.0); }':",
    options:["E' un costruttore che invoca un altro costruttore","E' errato perchè manca il tipo di ritorno","Genera un errore di compilazione","E' incompleto"],
    correct:0},
);

// === LEZIONE 043 - Encapsulation ===
QUESTIONS.push(
  {id:"L43Q1", lesson:"043", type:"chiusa", question:"Quale di queste affermazioni risulta corretta?",
    options:["La parola chiave this non si usa mai all'interno della classe","La parola chiave this nel costruttore si usa per ovviare a problemi di sovrapposizione di nomi","La parola chiave this nel costruttore non si usa mai","La parola chiave this si usa solo per compilare e nel costruttore"],
    correct:1},
  {id:"L43Q2", lesson:"043", type:"chiusa", question:"In Java il concetto di incapsulamento serve a:",
    options:["Incapsulare le istanze dei dati","Nascondere il codice","Nascondere le classi","Nascondere i dettagli implementativi di un Tipo di Dato Astratto"],
    correct:3},
  {id:"L43Q3", lesson:"043", type:"chiusa", question:"L'incapsulamento in Java:",
    options:["Consente di nascondere i dati","Consente di avere classi astratte","Consente di avere diverse implementazioni","Non si usa in Java"],
    correct:0},
  {id:"L43Q4", lesson:"043", type:"chiusa", question:"Uno dei vantaggi dell'incapsulamento è:",
    options:["Evitare che i metodi di una classe possano essere invocati da classi esterne","Nascondere i metodi di una classe","Bloccare l'accesso ai costruttori di una classe","Limitare gli effetti derivanti dalle eventuali modifiche future ad un sistema software"],
    correct:3},
  {id:"L43Q5", lesson:"043", type:"chiusa", question:"Per implementare l'incapsulamento in Java:",
    options:["Si evita l'accesso diretto alla classe da parte di classi esterne","Si evita l'accesso diretto ai metodi da parte del sistema operativo","Si evita l'accesso diretto ai metodi della classe da parte di classi esterne","Si evita l'accesso diretto agli attributi della classe da parte di classi esterne"],
    correct:3},
  {id:"L43Q6", lesson:"043", type:"chiusa", question:"Cosa possiamo dire della visibilità di una variabile in Java?",
    options:["E' visibile solo nei blocchi di codice che contengono il blocco in cui è dichiarata","E' visibile solo nel blocco in cui è stata dichiarata e nei blocchi in esso contenuti","E' visibile solo dal metodo main","E' visibile solo dai metodi che sono figli della classe di appartenenza"],
    correct:1},
  {id:"L43Q7", lesson:"043", type:"chiusa", question:"Una variabile dichiarata in un ciclo for è disponibile:",
    options:["Solo all'esterno del ciclo for e nel metodo","Solo all'esterno della classe e del ciclo for","Solo all'interno del ciclo for","Solo all'interno del main e nella classe"],
    correct:2},
  {id:"L43Q8", lesson:"043", type:"chiusa", question:"Una variabile locale ad un metodo:",
    options:["Si vede dal punto in cui viene dichiarata fino alla fine del blocco del metodo","Si vede nel metodo e nella classe a cui appartiene","Si vede al di fuori del blocco di codice in cui è stata dichiarata","Si vede dal punto in cui l'istanza viene creata con la new fino alla fine del programma che la contiene"],
    correct:0},
);

// === LEZIONE 044 - Exceptions ===
QUESTIONS.push(
  {id:"L44Q1", lesson:"044", type:"chiusa", question:"In Java si usano le eccezioni:",
    options:["Per gli errori in fase di compilazione","Solo per gestire gli errori di input/output da tastiera","Per gli errori in fase di scrittura","Per gli errori a run time per evitare interruzioni inattese del codice"],
    correct:3},
  {id:"L44Q2", lesson:"044", type:"chiusa", question:"Nel codice Java 'catch (NumberFormatException ex) {...}' la variabile 'ex':",
    options:["Indica una istanza di un metodo di emergenza","Indica una istanza di salvataggio del codice","Indica una istanza dell'errore che viene passata da chi genera l'errore","Indica una istanza di variabile per stampare messaggi a schermo"],
    correct:2},
  {id:"L44Q3", lesson:"044", type:"chiusa", question:"Quale delle seguenti affermazioni è certamente falsa?",
    options:["java.lang.Exception è la classe che gestisce gli errori a run time","java.lang.Exception serve a scrivere codice in modo eccezionalmente efficiente","java.lang.Exception è inclusa nelle API di Java","Le eccezioni sono sottoclassi di java.lang.Exception"],
    correct:1},
  {id:"L44Q4", lesson:"044", type:"chiusa", question:"Il seguente metodo: 'public int f(int num) throws DivisionePerZero {...}':",
    options:["Evita che venga generato un errore dal metodo","Solleva sempre un errore di DivisionePerZero al chiamante","Notifica sempre un errore al chiamante","Solleva un errore di DivisionePerZero per qualche input"],
    correct:2},
  {id:"L44Q5", lesson:"044", type:"chiusa", question:"Il blocco catch {...} serve a:",
    options:["Non serve in Java","Invoca il modulo di scrittura a schermo","Scrivere metodi per gestire gli errori di compilazione","Scrivere codice che gestisca l'eccezione a tempo di esecuzione"],
    correct:3},
  {id:"L44Q6", lesson:"044", type:"chiusa", question:"L'istruzione throw si usa per:",
    options:["Lanciare un metodo a tempo di compilazione","Lanciare una eccezione in modo programmatico","Gestire gli errori di compilazione","Bloccare il programma ed uscire"],
    correct:1},
  {id:"L44Q7", lesson:"044", type:"chiusa", question:"Il blocco try catch serve a:",
    options:["Provare ad agganciare un errore a tempo di compilazione","Agganciare un errore e gestirlo nel proprio codice","Agganciare gli errori di input output","Provare a scrivere meglio il codice"],
    correct:1},
  {id:"L44Q8", lesson:"044", type:"chiusa", question:"In Java la classe Exception:",
    options:["Serve a segnalare eccezioni di compilazione","Non si usa","Serve a definire dei metodi eccezionali","Serve a catturare gli errori come oggetto istanza della classe eccezione"],
    correct:3},
);

// === LEZIONE 048 - Interfaces ===
QUESTIONS.push(
  {id:"L48Q1", lesson:"048", type:"chiusa", question:"Nell'ereditarietà delle classi:",
    options:["Una classe si estende mentre una interfaccia non si usa","Una classe si implementa (implements) mentre una interfaccia si estende (extends)","Una classe si estende (extends) mentre una interfaccia si implementa (implements)","Una classe si estende mentre una superclasse non può essere usata"],
    correct:2},
  {id:"L48Q2", lesson:"048", type:"chiusa", question:"In Java le classi che implementano una interfaccia:",
    options:["Possono implementare tutti i metodi dell'interfaccia","Devono implementare tutti i metodi dell'interfaccia","Non implementano tutti i metodi dell'interfaccia","Implementano alcuni i metodi dell'interfaccia"],
    correct:1},
  {id:"L48Q3", lesson:"048", type:"chiusa", question:"In una interfaccia Java i metodi:",
    options:["Contengono instruzioni astratte","Non contengono istanze","Non contengono istruzioni","Contengono parametri"],
    correct:2},
  {id:"L48Q4", lesson:"048", type:"chiusa", question:"Una interfaccia in Java:",
    options:["Non può mai essere instanziata","Si può sempre istanziare","Si può istanziare ma solo nel metodo main()","Non si può mai istanziare tranne che nel metodo main()"],
    correct:0},
  {id:"L48Q5", lesson:"048", type:"chiusa", question:"Quale dei seguenti esempi rappresenta la definizione di una interfaccia in Java?",
    options:["private extends MiaInterfaccia","public MiaInterfaccia","public extends MiaInterfaccia","public interface MiaInterfaccia"],
    correct:3},
  {id:"L48Q6", lesson:"048", type:"chiusa", question:"Cosa è vero se ci si riferisce all'ereditarietà multipla in Java?",
    options:["Non esiste in Java","Una classe può avere più superclassi","Si implementa tramite l'uso di interfacce","Una classe può avere una e una sola sottoclasse"],
    correct:2},
  {id:"L48Q7", lesson:"048", type:"chiusa", question:"Data una classe Java Persona e le interfaccie Cantante e Vip, quali fra le seguenti definizioni della classe CantanteVip è la più corretta?",
    options:["public class CantanteVip extends Vip implements Persona, Cantante {...}","public class CantanteVip implements Persona, Cantante, Vip {...}","public class CantanteVip extends Persona implements Cantante, Vip {...}","public class CantanteVip extends Cantante implements Persona, Vip {...}"],
    correct:2},
  {id:"L48Q8", lesson:"048", type:"chiusa", question:"Tutti i metodi di una interfaccia:",
    options:["Devono essere privati","Devono essere pubblici","Devono essere implementati","Devono essere liberi"],
    correct:1},
);

// === LEZIONE 049 - Null ===
QUESTIONS.push(
  {id:"L49Q1", lesson:"049", type:"chiusa", question:"Dato un oggetto P di una classe C, a seguito dell'operazione 'p=null;' si ottiene che:",
    options:["Lo spazio di memoria occupato dall'oggetto p viene marcato come da conservare","Lo spazio di memoria di p contiene 0","Vengono settati a null tutti gli attributi dell'oggetto p","Lo spazio di memoria occupato dall'oggetto p viene marcato come da cancellare"],
    correct:3},
  {id:"L49Q2", lesson:"049", type:"chiusa", question:"L'errore 'error: variable p might not have been initialized' si genera se:",
    options:["La variabile p punta a dati non azzerati","La variabile p potrebbe non essere stata inizializzata","La variabile p non esiste","La variabile p esiste ma non ha dati diversi da zero"],
    correct:1},
  {id:"L49Q3", lesson:"049", type:"chiusa", question:"L'errore 'java.lang.NullPointerException' si genera:",
    options:["Se un oggetto contiene troppi dati","Se i puntatori degli oggetti si incrociano","Quando un oggetto è stato allocato ma gli attributi sono vuoti","Se si cerca di accedere ad una variabile che è stata associata a null"],
    correct:3},
  {id:"L49Q4", lesson:"049", type:"chiusa", question:"Le seguenti istruzioni in Java: Persona p=null; p.nome='Mario'; provocano:",
    options:["Un errore perchè p non punta ad alcuna locazione di memoria","Nessun effetto perchè p non esiste in memoria","La memorizzazione della stringa 'Mario' alla variabile nome di p","L'associazione di null alla variabile nome di p"],
    correct:0},
  {id:"L49Q5", lesson:"049", type:"chiusa", question:"Il Garbage Collector della Java Virtual Machine:",
    options:["Interviene quando si compila un programma","Interviene per liberare la memoria dopo che ad un oggetto viene assegnato null","Interviene quando si esegue un programma","Interviene per liberare la memoria dopo che termina un programma"],
    correct:1},
  {id:"L49Q6", lesson:"049", type:"chiusa", question:"In Java, quando si assegna il valore null ad un oggetto:",
    options:["Esso non esiste in memoria","Viene salvato come valore zero","Viene salvato come valore -1","Viene salvato come valore speciale e memorizzato nella locazione di memoria dell'oggetto"],
    correct:3},
  {id:"L49Q7", lesson:"049", type:"chiusa", question:"Una stringa String s che non è inizializzata:",
    options:["Contiene un valore nullo memorizzato in memoria","Non esiste come variabile e non può essere usata","Contiene un valore nullo ovvero non esiste in memoria","Non si può usare perchè vuota"],
    correct:2},
  {id:"L49Q8", lesson:"049", type:"chiusa", question:"In Java, relativamente ai valori nulli, le variabili definite come tipi complessi:",
    options:["Possono contenere valori nulli","Non possono contenere valori nulli","Possono contenere esclusivamente valori nulli","Possono contenere solo valori nulli"],
    correct:0},
);

// === LEZIONE 051 - Packages ===
QUESTIONS.push(
  {id:"L51Q1", lesson:"051", type:"chiusa", question:"Dove si trovano le funzioni della classe Math?",
    options:["Nel package java.hello","Nel package java.lang","Nel package java.Geometry","Nel package java.io"],
    correct:1},
  {id:"L51Q2", lesson:"051", type:"chiusa", question:"In Java un package:",
    options:["E' un pacchetto di strumenti per stampare","E' un pacchetto di variabili","E' uno strumento per raggruppare classi che abbiano una qualche similarità","E' uno strumento per raggruppare variabili"],
    correct:2},
  {id:"L51Q3", lesson:"051", type:"chiusa", question:"La sintassi gerarchica di un package Java è:",
    options:["dominio1.dominio2.dominio3","dominio1.Link.dominio2.Link.dominio3...","dominio1/dominio2/dominio3...","dominio1->dominio2->dominio3..."],
    correct:0},
  {id:"L51Q4", lesson:"051", type:"chiusa", question:"Un package si può utilizzare nel proprio codice usando la direttiva:",
    options:["define","export","import","use"],
    correct:2},
  {id:"L51Q5", lesson:"051", type:"chiusa", question:"Le classi del package java.lang:",
    options:["Sono importate automaticamente","Sono inutili","Sono rilevanti","Vanno importate dall'utente"],
    correct:0},
  {id:"L51Q6", lesson:"051", type:"chiusa", question:"Un package 'miopackage' si definisce all'inizio del codice con la dicitura:",
    options:["package newpackage miopackage","package miopackage","miopackage package","package new miopackage"],
    correct:1},
  {id:"L51Q7", lesson:"051", type:"chiusa", question:"Per importare tutte le classi al package 'miopackage' si usa:",
    options:["import All miopackage","import miopackage.*","import miopackage","import All class in miopackage"],
    correct:1},
  {id:"L51Q8", lesson:"051", type:"chiusa", question:"In relazione ai package, un programmatore può:",
    options:["Importare solo package che non siano i suoi","Definire ma non includere un proprio package","Definire ma non usare un proprio package","Definire ed usare un proprio package"],
    correct:3},
);

// === LEZIONE 052 - Access Modifiers ===
QUESTIONS.push(
  {id:"L52Q1", lesson:"052", type:"chiusa", question:"A cosa servono i modificatori di accesso?",
    options:["A stabilire la correttezza di un attributo o di un metodo","A stabilire le politiche di visibilità di un attributo o di un metodo","A modificare l'accesso di un attributo ma non di un metodo","A verificare le politiche di visibilità di un attributo o di un metodo"],
    correct:1},
  {id:"L52Q2", lesson:"052", type:"chiusa", question:"Come si definisce in Java la politica di accesso di un metodo?",
    options:["Verificandone la correttezza formale","Con l'indice di livello del metodo","Con le politiche di programmazione","Con un modificatore di accesso"],
    correct:3},
  {id:"L52Q3", lesson:"052", type:"chiusa", question:"A cosa serve la visibilità public?",
    options:["A inibire l'accesso di un metodo alle sottoclassi","A rendere accessibile il metodo main al Sistema Operativo","A pubblicare un metodo in un package","A inibire l'accesso di un metodo alla superclasse"],
    correct:1},
  {id:"L52Q4", lesson:"052", type:"chiusa", question:"Per quale motivo si usa il livello di visibilità private?",
    options:["Per rendere metodi e attributi inaccessibili anche dalla classe che li contiene","Per rendere attributi accessibili solo dalle sottoclassi","Per rendere metodi inaccessibili e incapsulare attributi","Per rendere metodi accessibili solo da classi dello stesso package"],
    correct:2},
  {id:"L52Q5", lesson:"052", type:"chiusa", question:"Per quale motivo si usa il livello di visibilità protected?",
    options:["Per permettere l'accesso ad attributi e metodi anche alle sottoclassi","Per permettere l'accesso solo da classi dello stesso package","Per proteggere l'accesso di metodi e attributi da parte di tutte le altre classi","Per rendere metodi accessibili solo da classi dello stesso package"],
    correct:0},
  {id:"L52Q6", lesson:"052", type:"chiusa", question:"Per quale motivo si usa il livello di visibilità package?",
    options:["Per permettere l'accesso solo da classi dello stesso package","Per rendere metodi inaccessibili e incapsulare attributi","Per rendere package inaccessibili","Per permettere l'accesso ad attributi e metodi anche alle sottoclassi"],
    correct:0},
  {id:"L52Q7", lesson:"052", type:"chiusa", question:"Nel linguaggio Java esiste la possibilità di rendere una risorsa non accessibile anche alla classe cui appartiene?",
    options:["No","Si","Dipende dal contesto","Nessuna risposta è quella corretta"],
    correct:1},
  {id:"L52Q8", lesson:"052", type:"chiusa", question:"Quanti sono e con quale parola chiave si indicano i livelli di visibilità in Java?",
    options:["Sono 4, indicati con 'public', 'private', 'protected' e ''","Sono 2, indicati con 'public' e 'private'","Sono 3, indicati con 'public', 'private' e 'protected'","Sono 4, indicati con 'public', 'private', 'protected' e 'package'"],
    correct:0},
);

// === LEZIONE 053 - Object Class ===
QUESTIONS.push(
  {id:"L53Q1", lesson:"053", type:"chiusa", question:"Il metodo 'public boolean equals(Object obj)':",
    options:["Ritorna 0 se l'oggetto passato come parametro è uguale a quello corrente","Ritorna false se l'oggetto passato come parametro è uguale a quello corrente","Ritorna true se l'oggetto passato come parametro è uguale a quello corrente","Ritorna 1 se l'oggetto passato come parametro è uguale a quello corrente"],
    correct:2},
  {id:"L53Q2", lesson:"053", type:"chiusa", question:"La classe Object di Java fa parte di:",
    options:["Del package java.input","Del package java.lang","Del package java.output","Di nessun package"],
    correct:1},
  {id:"L53Q3", lesson:"053", type:"chiusa", question:"La funzione 'public String toString()' cosa fa?",
    options:["Ritorna una rappresentazione in formato float dell'oggetto","Ritorna una rappresentazione in formato stringa dell'oggetto","Ritorna una rappresentazione in formato intera dell'oggetto","Ritorna una rappresentazione in formato double dell'oggetto"],
    correct:1},
  {id:"L53Q4", lesson:"053", type:"chiusa", question:"L'espressione '!(obj instanceof NomeClasse)':",
    options:["Genera un errore se obj è una istanza della classe NomeClasse","Ritorna true se obj è una istanza della classe NomeClasse","Ritorna sempre false","Ritorna false se obj è una istanza della classe NomeClasse"],
    correct:3},
  {id:"L53Q5", lesson:"053", type:"chiusa", question:"Per definire un ordinamento esiste l'interfaccia Comparable. Per usarla bisogna:",
    options:["Definire oggetti dell'interfaccia","Implementare i metodi dell'interfaccia","Istanziare oggetti dell'interfaccia","Usare i metodi dell'interfaccia"],
    correct:1},
  {id:"L53Q6", lesson:"053", type:"chiusa", question:"La funzione 'protected Object clone()' della classe Object:",
    options:["Crea e ritorna un puntatore all'oggetto","Crea e ritorna una copia degli oggetti in memoria","Crea e ritorna una copia di tutti gli Object","Crea e ritorna una copia di questo oggetto"],
    correct:3},
  {id:"L53Q7", lesson:"053", type:"chiusa", question:"La funzione della classe oggetto 'int compareTo(Object o)':",
    options:["Ritorna false se l'oggetto su cui si invoca il metodo non è uguale a 'o'","Ritorna uno se l'oggetto su cui si invoca il metodo è uguale a 'o'","Ritorna uno se l'oggetto su cui si invoca il metodo è maggiore di 'o'","Ritorna true se l'oggetto su cui si invoca il metodo è uguale a 'o'"],
    correct:2},
  {id:"L53Q8", lesson:"053", type:"chiusa", question:"Il metodo 'protected void finalize()' è chiamato:",
    options:["dal Garbage Collector quando esso rileva che l'oggetto corrente non è più raggiungibile","dal compilatore quando esso rileva che l'oggetto corrente non è più raggiungibile","dal Sistema Operativo quando esso rileva che l'oggetto corrente non è più raggiungibile","dall'utente quando esso rileva che l'oggetto corrente non è più raggiungibile"],
    correct:0},
);

// === LEZIONE 056 - Random Numbers ===
QUESTIONS.push(
  {id:"L56Q1", lesson:"056", type:"chiusa", question:"Il metodo Math.random():",
    options:["Genera numeri double pseudocasuali fra 0 e 1","Genera numeri double pseudocasuali fra 1 e 10","Genera numeri interi pseudocasuali fra 0 e 1","Genera numeri interi pseudocasuali fra 1 e 10"],
    correct:0},
  {id:"L56Q2", lesson:"056", type:"chiusa", question:"E' possibile generare numeri casuali:",
    options:["usando esclusivamente hardware","sia usando algoritmi software che, in alcuni casi, usando hardware","usando esclusivamente codice scritto dall'utente","usando esclusivamente codice del sistema operativo"],
    correct:1},
  {id:"L56Q3", lesson:"056", type:"chiusa", question:"Come si possono generare numeri pseudocasuali in Java?",
    options:["Si può utilizzare la classe RandomNumber","Si può utilizzare sia la classe Random che la classe Math","Si può utilizzare il metodo Math.pseudorandom()","Si può utilizzare la classe PseudoRandom"],
    correct:1},
  {id:"L56Q4", lesson:"056", type:"chiusa", question:"Quali sono le proprietà che deve soddisfare una sequenza di numeri pseudocasuali?",
    options:["devono essere indipendenti","devono essere distribuiti uniformemente e devono essere indipendenti fra di loro","devono essere distribuiti in modo costante","devono essere generati uno di seguito all'altro nell'intervallo di definizione"],
    correct:1},
  {id:"L56Q5", lesson:"056", type:"chiusa", question:"Considerando l'intervallo [1,10], la sequenza di numeri {1,2,3,4,5,6,7,8,9,10} non è pseudocasuale perchè:",
    options:["non soddisfa la proprietà di indipendenza fra i numeri","i numeri sono interi e non double","i numeri non sono distribuiti equamente nell'intervallo","i numeri non sono sufficientemente casuali"],
    correct:0},
  {id:"L56Q6", lesson:"056", type:"chiusa", question:"La classe Random:",
    options:["genera numeri pseudocasuali solo interi","genera numeri pseudocasuali solo interi e solo nell'intervallo [0,n]","genera numeri pseudocasuali solo double","genera numeri pseudocasuali interi e double"],
    correct:3},
  {id:"L56Q7", lesson:"056", type:"chiusa", question:"Da cosa è generato un numero pseudocasuale?",
    options:["da un algoritmo ricorsivo","da un algoritmo deterministico","da un algoritmo casuale","da un algoritmo random"],
    correct:1},
  {id:"L56Q8", lesson:"056", type:"chiusa", question:"Quali caratteristiche ha un numero pseudocasuale?",
    options:["ha proprietà sia ricorsive che iterative","ha proprietà numeriche di tipo esponenziale","ha proprietà statistiche simili a quelle di un processo casuale","ha proprietà sia simmetriche che transitive"],
    correct:2},
);

// === LEZIONE 057 - Linked Lists ===
QUESTIONS.push(
  {id:"L57Q1", lesson:"057", type:"chiusa", question:"Quale delle seguenti frasi è errata se riferita alla classe Nodo di una Lista?",
    options:["La classe Nodo rappresenta un elemento di una Lista","La classe Nodo contiene le informazioni strutturali di una Lista","La classe Nodo permette di manipolare gli elementi di una Lista","La classe Nodo contiene le informazioni topologiche di una Lista"],
    correct:1},
  {id:"L57Q2", lesson:"057", type:"chiusa", question:"Cosa sono le proprietà topologiche di una lista?",
    options:["Le sue proprietà di memorizzazione","Le sue proprietà dimensionali","Le sue proprietà dinamiche","Le sue proprietà geometriche"],
    correct:2},
  {id:"L57Q3", lesson:"057", type:"chiusa", question:"Perchè si introduce il Tipo di Dato Astratto Lista?",
    options:["Per migliorare la gestione della memoria di Java","Per supportare meglio gli array nella gestione della memoria","Per superare le limitazioni del tipo di dato array","Per allocare zone di memoria contigue più ampie rispetto agli array"],
    correct:2},
  {id:"L57Q4", lesson:"057", type:"chiusa", question:"Cos'è un oggetto della classe Lista?",
    options:["Un tipo di dato base","Un oggetto dinamico","Un oggetto statico","Un tipo di dato astratto"],
    correct:3},
  {id:"L57Q5", lesson:"057", type:"chiusa", question:"Quale fra queste caratteristiche non è corretta se riferita alle Liste?",
    options:["La sua lunghezza non è fissa","I suoi elementi occupano celle di memoria contigue","I suoi elementi non occupano celle di memoria contigue","Aggiungere o eliminare un elemento è indipendente dalla sua posizione"],
    correct:1},
  {id:"L57Q6", lesson:"057", type:"chiusa", question:"Quale fra le seguenti metafore è stata usata a lezione per descrivere le Liste?",
    options:["La metafora delle perle e dei ganci","La metafora dell'ago e del filo","La metafora del nastro illimitato","La metafora del filo annodato"],
    correct:0},
  {id:"L57Q7", lesson:"057", type:"chiusa", question:"Lo schema del Nodo studiato a lezione:",
    options:["contiene un solo attributo","contiene due attributi, info e next","contiene due attributi, uno che punta al nodo precedente ed uno al successivo","contiene l'attributo next e un puntatore a se stesso"],
    correct:1},
  {id:"L57Q8", lesson:"057", type:"chiusa", question:"La definizione dell'attributo next nella classe Nodo:",
    options:["ne rende la definizione ricorsiva","ne rende la definizione nulla","ne rende la definizione iterativa","ne rende la definizione incongruente"],
    correct:0},
);

// === LEZIONE 058 - Singly Linked Lists ===
QUESTIONS.push(
  {id:"L58Q1", lesson:"058", type:"chiusa", question:"Quando una classe Lista semplicemente linkata viene creata, come viene inizializzata la testa della lista?",
    options:["Eliminando il nodo di testa","Azzerando il nodo di testa","Con il valore null","Con il valore -1"],
    correct:2},
  {id:"L58Q2", lesson:"058", type:"chiusa", question:"Un elemento nodo di una Lista semplicemente linkata:",
    options:["Contiene un attributo info e un riferimento al nodo precedente","Contiene un riferimento al nodo successivo","Contiene un riferimento al nodo precedente ed al successivo","Contiene un riferimento al nodo precedente"],
    correct:1},
  {id:"L58Q3", lesson:"058", type:"chiusa", question:"Gli attributi info e next della classe Nodo di una Lista semplicemente linkata:",
    options:["sono dichiarati private e sono accessibili tramite i metodi getter e setter","sono dichiarati private e non sono accessibili se non dalla classe","sono solitamente dichiarati static","sono solitamente dichiarati public"],
    correct:0},
  {id:"L58Q4", lesson:"058", type:"chiusa", question:"Qual è il simbolo per raffigurare graficamente che l'attributo next di un Nodo di una Lista vale null?",
    options:["Un quadrato vuoto","La cifra zero","Il simbolo di insieme vuoto","Il simbolo elettrico di messa a terra"],
    correct:3},
  {id:"L58Q5", lesson:"058", type:"chiusa", question:"Quale fra le seguenti caratteristiche non è riferita ad una Lista semplicemente linkata?",
    options:["Gli elementi che la compongono non occupano locazioni di memoria contigue","Il numero dei suoi elementi viene fissato dal costruttore","In generale, sono più efficienti nell'aggiunta di elementi rispetto agli array","Il numero dei suoi elementi può variare durante l'esecuzione del programma"],
    correct:1},
  {id:"L58Q6", lesson:"058", type:"chiusa", question:"Nella classe Lista semplicemente linkata:",
    options:["Esiste un riferimento a tutti i nodi","Esiste un riferimento alla coda","Non esiste riferimento ad alcun nodo","Esiste un riferimento alla testa"],
    correct:3},
  {id:"L58Q7", lesson:"058", type:"chiusa", question:"Di solito, quali attributi sono presenti nella classe Nodo di una Lista semplicemente linkata?",
    options:["next e previous","head e tail","head e next","info e next"],
    correct:3},
  {id:"L58Q8", lesson:"058", type:"chiusa", question:"Dato il nodo n di una Lista semplicemente linkata definito come 'Nodo n = new Nodo(1);' come posso collegargli un nuovo nodo contenente il valore 2?",
    options:["n.addNodo(new Nodo(2));","n.setNext(new Nodo(2));","n+=new Nodo(2);","n.setNext(2);"],
    correct:1},
);

// === LEZIONE 060 - List Search ===
QUESTIONS.push(
  {id:"L60Q1", lesson:"060", type:"chiusa", question:"Che differenza c'è tra la ricerca di un nodo in una Lista ordinata o non ordinata?",
    options:["In media la ricerca in una lista ordinata è più efficiente","Possiamo effettuare la ricerca sono in liste ordinate","Possiamo partire dalla testa nel primo caso e dalla coda nel secondo caso","Sono identiche"],
    correct:0},
  {id:"L60Q2", lesson:"060", type:"chiusa", question:"Se effettuiamo la ricerca di un nodo in una Lista vuota:",
    options:["La ricerca non si può fare e viene generata un'eccezione di lista vuota","La ricerca va avanti e restituisce comunque un risultato","La JVM gestisce automaticamente l'eccezione rilevando che il primo nodo è null","Il compilatore genera un errore perchè rileva che il primo nodo è null"],
    correct:2},
  {id:"L60Q3", lesson:"060", type:"chiusa", question:"Dato un nodo di una classe Lista, l'istruzione 'aux = aux.getNext()':",
    options:["Scorre in avanti al prossimo nodo assegnando al valore aux l'indirizzo contenuto in aux.next","E' ricorsiva e non si può eseguire","Scorre in avanti al prossimo nodo assegnando al valore aux l'indirizzo contenuto in aux","Scorre indietro al nodo precedente assegnando al valore aux l'indirizzo contenuto in aux"],
    correct:0},
  {id:"L60Q4", lesson:"060", type:"chiusa", question:"L'espressione '(aux!=null && aux.getInfo()<key)' con aux variabile ausiliaria Nodo di una Lista:",
    options:["Vale true se aux punta ad un nodo inesistente","Vale true se aux punta ad un nodo esistente (non nullo) o se il valore info contenuto nel nodo è minore di 'key'","Vale true se aux punta ad un nodo esistente (non nullo) e se il valore info contenuto nel nodo è minore di 'key'","Vale true se aux punta ad un nodo esistente (non nullo) e se l'attributo info contenuto nel nodo è maggiore di 'key'"],
    correct:2},
  {id:"L60Q5", lesson:"060", type:"chiusa", question:"Nel caso di ricerca di un nodo avente 'info=3' in una Lista ordinata di interi:",
    options:["La ricerca visita la lista e per ogni nodo se trova il valore 3 si ferma e ritorna il riferimento al nodo","La ricerca visita la lista e per ogni nodo se trova il valore 3 continua a visitare e ritorna il riferimento al nodo","La ricerca visita tutta la lista e se trova il valore 3 in una info ritorna true e continua a visitare la lista","La ricerca visita tutta la lista e se trova il valore 3 in una info cancella il resto della lista e ritorna il riferimento al nodo"],
    correct:0},
  {id:"L60Q6", lesson:"060", type:"chiusa", question:"L'espressione '(aux != null && aux.getInfo() == key)' ritorna:",
    options:["True se il valore della variabile aux è null e se il contenuto dell'info nel nodo è diverso al valore key","True se il valore della variabile aux è non null e se il contenuto dell'info nel nodo è diverso al valore key","True se il valore della variabile aux è non null e se il contenuto dell'info nel nodo è pari al valore key","True se il valore della variabile aux è non null o se il contenuto dell'info nel nodo è diverso al valore key"],
    correct:2},
  {id:"L60Q7", lesson:"060", type:"chiusa", question:"La ricerca di un nodo in una Lista ordinata:",
    options:["E' possibile ma più complicata se la lista è ordinata","Non è possibile","E' possibile e se ordinata è più veloce","E' possibile ma dipende dal tipo di nodo"],
    correct:2},
);